package com.workplace.mail.outbound;

import java.util.List;

/** ai-agent /mail/* 요청·응답 계약. assistant 설정(agentId/model/maxTurns/timeoutMs)은 요청 본문으로 전달. */
public final class MailAiMessages {
  private MailAiMessages() {}

  /** 스레드 메시지 1건(답장 초안 컨텍스트). */
  public record ThreadMessage(String from, String date, String body) {}

  public record ReplyDraftRequest(
      List<ThreadMessage> thread,
      String replyingAs,
      long assistantAgentId,
      String model,
      int maxTurns,
      int timeoutMs) {}

  public record ReplyDraftResult(String draftBody) {}

  /** 초안 코칭 노트 1건(ai-agent 와이어). */
  public record CoachingNoteWire(String dimension, String message) {}

  /** 초안 코칭 요청: 초안 평문 + (답장이면) 원문 스레드. 새 메일이면 thread 빈 리스트. */
  public record DraftCoachingRequest(
      String draftBody,
      List<ThreadMessage> thread,
      String replyingAs,
      long assistantAgentId,
      String model,
      int maxTurns,
      int timeoutMs) {}

  /** 초안 코칭 결과: 코칭 노트 목록 + 다듬은 개선본 HTML. */
  public record DraftCoachingResult(List<CoachingNoteWire> notes, String improvedBodyHtml) {}

  /** #520 이슈 초안 요청. candidateProjects 로 AI 가 projectKey 를 고른다. */
  public record IssueDraftRequest(
      String subject,
      String body,
      java.util.List<CandidateProject> candidateProjects,
      long assistantAgentId,
      String model,
      int maxTurns,
      int timeoutMs) {}

  /** 후보 프로젝트(key+name) — ai-agent 전송용. */
  public record CandidateProject(String key, String name) {}

  /** #520 이슈 초안 응답. suggestedProjectKey 는 후보 중 하나 또는 null. */
  public record IssueDraftResult(String title, String body, String priority, String projectKey) {}

  /**
   * WP-149 ③ 원본 분석 요청 — 제목·보낸 사람·새 본문(자동 발송이면 미리보기). include* 로 받을 항목을 고른다(생략 항목은 agent 가 지시·필드 자체를
   * 뺀다).
   */
  public record AnalyzeContentRequest(
      String subject,
      String from,
      String body,
      boolean autoGenerated,
      boolean includeCategory,
      boolean includeSummary,
      long assistantAgentId,
      String model,
      int maxTurns,
      int timeoutMs) {}

  /** ③ 응답 — 요청하지 않았거나 형식이 틀린 항목은 null. */
  public record AnalyzeContentResult(String category, String summary) {}

  /**
   * WP-149 ④ 개인 분석 요청 — "나" 기준 회신필요·개인 요약·(공통 비서가 없을 때) 분류. WP-150 이 "나" 프로필·보낸 사람 관계·이전 메일·연결
   * 이슈·첨부 이름을 더했다. 조회에 실패한 블록은 null(sender·linkedIssue) 또는 빈 목록(thread·attachments)으로 보내고, agent 는
   * 그 블록을 뺀다(ai-agent zod 는 모든 보강 필드를 nullish 로 받는다).
   *
   * @param autoGenerated 대량·자동 발송 원본(본문 자리에 미리보기가 올 수 있음)
   */
  public record AnalyzePersonalRequest(
      String subject,
      String fromAddress,
      String fromName,
      String body,
      boolean autoGenerated,
      Me me,
      Recipient recipient,
      Sender sender,
      List<PriorMail> thread,
      IssueRef linkedIssue,
      List<String> attachments,
      boolean includeNeedsReply,
      boolean includePersonalSummary,
      boolean includeCategory,
      long assistantAgentId,
      String model,
      int maxTurns,
      int timeoutMs) {}

  /** "나" 블록(WP-150) — 주소(소문자, ⑤ 규칙과 같은 집합)·이름·다른 이름(계정 표시 이름)·직함·소속 조직. 프로필 조회에 실패하면 주소만 채운다. */
  public record Me(
      List<String> addresses,
      String name,
      List<String> otherNames,
      String title,
      List<String> groups) {

    /** 주소만 있는 "나". */
    public Me(List<String> addresses) {
      this(addresses, null, List.of(), null, List.of());
    }
  }

  /** 보낸 사람과 나의 관계(WP-150). relation = SELF|MEMBER|CONTACT|UNKNOWN(SenderRelation.Kind 이름). */
  public record Sender(
      String relation,
      String name,
      String title,
      String organization,
      List<String> sameGroups,
      boolean favorite) {}

  /**
   * 같은 스레드의 이전 메일 1건(WP-150) — from 은 "이름 <주소>" 또는 주소, date 는 received_at ISO, body 는 새로 쓴 부분 앞
   * 500자.
   */
  public record PriorMail(boolean fromMe, String from, String date, String body) {}

  /** 이 메일로 만든 이슈(WP-150). key = "{프로젝트키}-{번호}", status = TODO|IN_PROGRESS|DONE|CANCELED. */
  public record IssueRef(String key, String title, String status) {}

  /** 받는 사람 블록 — myRole: TO|CC|NONE|UNKNOWN(NeedsReplyRules.RecipientRole 이름). */
  public record Recipient(String myRole, int toCount, int ccCount) {}

  /**
   * ④ 응답. needsReply 는 요청했을 때만 값이 있다(요약만 모드는 null). personalSummaryValid=false 면 개인 요약을 요청하지 않았거나
   * 형식이 틀린 것 — 개인 요약은 기록하지 않는다.
   */
  public record AnalyzePersonalResult(
      Boolean needsReply, String personalSummary, boolean personalSummaryValid, String category) {}
}
