package com.workplace.mail.dto;

import java.util.List;

/**
 * 본문 전용 파싱 결과(OnDemand/백그라운드 본문 적재용).
 *
 * @param autoGenerated WP-149 ② 대량·자동 발송 헤더 판정 결과(헤더 원문은 저장하지 않음)
 */
public record ParsedBody(
    String bodyText,
    String bodyHtml,
    String snippet,
    boolean hasAttachment,
    List<ParsedAttachment> attachments,
    boolean autoGenerated) {}
