package com.workplace.mail.service;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.workplace.mail.dto.BodyTarget;
import com.workplace.mail.dto.EmailAccountResponse;
import com.workplace.mail.dto.MailProvider;
import com.workplace.mail.dto.ParsedAttachment;
import com.workplace.mail.outbound.GraphApiClient;
import com.workplace.mail.repository.EmailAttachmentRepository;
import com.workplace.mail.repository.EmailMessageRepository;
import com.workplace.mail.util.AutoGeneratedHeaders;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Microsoft Graph 공급자용 {@link MailBodyLoader} 구현.
 *
 * <p>Graph API에서 메시지 본문(body.contentType/body.content)과 첨부 메타를 조회해 DB에 캐시한다. 멱등
 * 가드(body_fetched_at)와 AI 분류 트리거는 {@link MailBodyFetcher} 디스패처가 처리하므로 이 loader는 순수 적재만 담당한다.
 *
 * <p>Graph API 특성:
 *
 * <ul>
 *   <li>body.contentType: "html" 또는 "text" — 각각 bodyHtml/bodyText 에 저장.
 *   <li>bodyPreview: 스니펫(최대 255자, Graph 응답 그대로 사용).
 *   <li>첨부 메타: GET /me/messages/{id}/attachments?$select=id,name,contentType,size,isInline. 본문이
 *       cid: 를 참조하면 인라인 첨부만 단건 조회해 Content-ID 저장(WP-68).
 *   <li>네트워크/파싱 오류는 best-effort 로 삼킨다(로그만, 토큰 평문 미출력).
 * </ul>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class GraphBodyLoader implements MailBodyLoader {

  private final EmailMessageRepository messageRepo;

  /** WP-130: 본문을 공유 content 에 기록·검증(불일치 시 분리). */
  private final MailContentShareGate shareGate;

  private final EmailAttachmentRepository attachmentRepo;
  private final GraphTokenService graphTokenService;
  private final GraphApiClient graphApiClient;

  /** WP-68: 인라인 첨부 Content-ID 단건 조회. */
  private final GraphInlineContentIdResolver contentIdResolver;

  @Override
  public MailProvider provider() {
    return MailProvider.M365_GRAPH;
  }

  /**
   * Graph API에서 단건 메시지 본문을 적재한다.
   *
   * <p>providerMessageId 가 null 이면 Graph 메시지 조회가 불가하므로 false 반환한다. body.contentType="html" 이면
   * bodyHtml 에, "text" 이면 bodyText 에 저장한다. 첨부 메타는 hasAttachments=true 이거나 본문이 cid: 를 참조할 때만 추가
   * 조회한다.
   *
   * <p>Task5: 본문·스니펫은 email_content 에 기록(MailContentShareGate — 첫 적재자 선점, 불일치 시 분리). has_attachment
   * 만 envelope 에 남긴다. contentId=0 이면 content 미연결 — false 반환.
   *
   * @return true: 적재 성공(공유 content 기록·검증 완료). false: providerMessageId 없음·contentId=0·네트워크/파싱
   *     실패(재시도 가능). 적재 실패 시 분류 skip — 빈 스니펫 기반 영구 오분류 방지(I1 수정).
   */
  @Override
  public boolean loadBody(long userId, BodyTarget target, EmailAccountResponse account) {
    String providerMessageId = target.providerMessageId();
    if (providerMessageId == null) {
      // Graph 계정이지만 provider_message_id 없음 — 적재 불가, 분류도 skip
      log.warn("GraphBodyLoader: provider_message_id 없음 (messageId={})", target.messageId());
      return false;
    }
    // contentId=0: content 행이 연결되지 않은 legacy envelope — 본문 저장 불가
    if (target.contentId() == 0L) {
      log.warn("GraphBodyLoader: content_id 없음 — 적재 skip (messageId={})", target.messageId());
      return false;
    }

    try {
      String accessToken = graphTokenService.getAccessToken(userId, target.accountId());

      // 본문·스니펫·첨부플래그 조회
      // WP-149 ②: 자동 발송 판정을 위해 internetMessageHeaders 도 함께 받는다(원문은 저장하지 않음)
      String msgUrl =
          "/me/messages/"
              + providerMessageId
              + "?$select=body,bodyPreview,hasAttachments,internetMessageHeaders";
      GraphMessageBody msgResp = graphApiClient.get(accessToken, msgUrl, GraphMessageBody.class);

      String bodyHtml = null;
      String bodyText = null;
      if (msgResp.body() != null) {
        // body.contentType: "html" | "text" (대소문자 무관)
        String ct = msgResp.body().contentType();
        if ("html".equalsIgnoreCase(ct)) {
          bodyHtml = msgResp.body().content();
        } else {
          bodyText = msgResp.body().content();
        }
      }

      String snippet = msgResp.bodyPreview();
      boolean hasAttachment = Boolean.TRUE.equals(msgResp.hasAttachments());

      // 첨부 메타 조회 — hasAttachments=true 이거나 본문이 cid: 를 참조할 때만 추가 Graph 호출.
      // Graph hasAttachments 는 인라인 첨부를 세지 않아, 인라인 이미지만 있는 메일도 cid 참조로 판정해 적재한다(WP-68).
      // WP-130: 공유 content 검증에 첨부 목록이 필요하므로 본문 기록보다 먼저 조회한다.
      boolean bodyRefsCid = InlineImageSupport.refsCid(bodyHtml);
      List<ParsedAttachment> attachments =
          hasAttachment || bodyRefsCid
              ? fetchAttachmentMeta(accessToken, providerMessageId, target.messageId(), bodyRefsCid)
              : List.of();

      // 본문·스니펫은 공유 content 에 기록 — WP-130: 이미 기록돼 있으면 해시·첨부 목록을 검증하고, 다르면 이 envelope 만 분리
      long contentId =
          shareGate.storeFetchedBody(
              target.messageId(), target.contentId(), bodyText, bodyHtml, snippet, attachments);
      // 늦게 표시된 경우 같은 content 의 이미 판정된 사본들의 ⑤ 도 다시 계산한다
      shareGate.recordAutoGenerated(contentId, autoGenerated(msgResp.internetMessageHeaders()));
      // has_attachment 는 envelope 속성(첨부 존재 표시)으로 유지
      messageRepo.markHasAttachment(target.messageId(), hasAttachment);
      attachmentRepo.insertAll(target.messageId(), contentId, attachments);
      // V97: per-envelope 마커 — 이 envelope 의 본문/첨부 적재가 완료됐음을 기록
      messageRepo.markFetched(target.messageId());
      return true;
    } catch (Exception e) {
      // 토큰·민감정보 노출 방지 — messageId 와 예외 요약만 기록
      // false 반환 — 적재 실패 시 분류 skip(빈 스니펫 기반 영구 오분류 방지).
      log.warn("Graph 본문 적재 실패 (messageId={}): {}", target.messageId(), e.toString());
      return false;
    }
  }

  /**
   * Graph 첨부 메타를 조회한다(DB 쓰기 없음 — 삽입은 {@link EmailAttachmentRepository#insertAll}). 실패는 best-effort
   * 로 빈 목록.
   *
   * <p>GET /me/messages/{id}/attachments?$select=id,name,contentType,size,isInline —
   * 바이너리(contentBytes) 는 요청하지 않는다(메타만). id 를 provider_attachment_id 로 저장해 다운로드 시 ordinal 의존 없이 직접
   * 조회할 수 있도록 한다. 반환 목록의 인덱스가 ordinal 이다.
   *
   * <p>WP-68: 본문이 cid: 를 참조하면 인라인·소용량 첨부만 단건 조회해 Content-ID 를 함께 저장한다(프론트가 cid → 첨부 매칭). 서명 로고 같은
   * 인라인 첨부는 거의 모든 메일에 있으므로, 본문에 cid 참조가 없으면 추가 호출하지 않는다.
   */
  List<ParsedAttachment> fetchAttachmentMeta(
      String accessToken, String providerMessageId, long messageId, boolean bodyRefsCid) {
    try {
      String url =
          "/me/messages/"
              + providerMessageId
              + "/attachments?$select=id,name,contentType,size,isInline";
      GraphAttachmentList listResp =
          graphApiClient.get(accessToken, url, GraphAttachmentList.class);

      if (listResp == null || listResp.value() == null) {
        return List.of();
      }
      List<ParsedAttachment> result = new ArrayList<>();
      for (GraphAttachmentItem item : listResp.value()) {
        long size = item.size() != null ? item.size() : 0L;
        String mimeContentId =
            bodyRefsCid
                    && Boolean.TRUE.equals(item.isInline())
                    && size <= GraphInlineContentIdResolver.MAX_INLINE_BYTES
                ? contentIdOrNull(accessToken, providerMessageId, item)
                : null;
        result.add(
            new ParsedAttachment(
                item.name(),
                item.contentType(),
                size,
                mimeContentId,
                item.id() // Graph 첨부 안정 id — 다운로드 경로에서 사용
                ));
      }
      return result;
    } catch (Exception e) {
      // 첨부 메타 조회 실패는 best-effort — 본문 적재는 계속(첨부 없음으로 처리)
      log.warn("Graph 첨부 메타 조회 실패 (messageId={}): {}", messageId, e.toString());
      return List.of();
    }
  }

  /**
   * 적재 중 Content-ID 조회 — 실패는 해당 항목만 null 로 흡수해 이후 첨부 적재를 막지 않는다. null 로 남은 행은 열람 시 지연 백필({@link
   * MailInlineContentIdBackfiller})이 다시 시도한다.
   */
  private String contentIdOrNull(
      String accessToken, String providerMessageId, GraphAttachmentItem item) {
    try {
      return contentIdResolver.fetchContentId(accessToken, providerMessageId, item.id());
    } catch (Exception e) {
      // 토큰 노출 방지 — 예외 요약만
      log.warn("Graph 첨부 Content-ID 조회 실패(적재 계속): {}", e.toString());
      return null;
    }
  }

  // ---- Graph API 응답 역직렬화 DTO (내부 전용) ----

  /** WP-149 ②: Graph 헤더 목록으로 자동 발송 여부를 판정한다. 이름은 대소문자를 무시한다. 헤더가 없으면(권한·구형 응답) false. */
  public static boolean autoGenerated(List<GraphHeader> headers) {
    if (headers == null || headers.isEmpty()) {
      return false;
    }
    Map<String, List<String>> byName = new HashMap<>();
    for (GraphHeader h : headers) {
      if (h == null || h.name() == null) {
        continue;
      }
      byName
          .computeIfAbsent(h.name().toLowerCase(Locale.ROOT), k -> new ArrayList<>())
          .add(h.value());
    }
    return AutoGeneratedHeaders.detect(
        name -> byName.getOrDefault(name.toLowerCase(Locale.ROOT), List.of()));
  }

  /** GET /me/messages/{id}?$select=body,bodyPreview,hasAttachments,internetMessageHeaders 응답. */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record GraphMessageBody(
      ItemBody body,
      String bodyPreview,
      Boolean hasAttachments,
      List<GraphHeader> internetMessageHeaders) {

    /** 헤더 없이 생성(기존 테스트·헤더 미요청 경로 호환). */
    public GraphMessageBody(ItemBody body, String bodyPreview, Boolean hasAttachments) {
      this(body, bodyPreview, hasAttachments, null);
    }
  }

  /** Graph internetMessageHeaders 항목(name/value). */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record GraphHeader(String name, String value) {}

  /** Graph body 객체. contentType: "html"|"text", content: 본문 문자열. */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record ItemBody(String contentType, String content) {}

  /** GET /me/messages/{id}/attachments 응답(value 배열). */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record GraphAttachmentList(List<GraphAttachmentItem> value) {}

  /**
   * 단일 첨부 메타 항목. id 는 Graph 첨부 안정 식별자 — 다운로드 직접 조회에 사용. isInline 은 본문 인라인 여부(WP-68, Content-ID 단건
   * 조회 후보 판정).
   */
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record GraphAttachmentItem(
      String id,
      String name,
      String contentType,
      @JsonProperty("size") Long size,
      Boolean isInline) {}
}
