package com.workplace.mail.service;

import com.workplace.auth.service.AssistantResolver;
import com.workplace.auth.service.AssistantSpec;
import com.workplace.mail.outbound.AiAgentMailClient;
import com.workplace.mail.outbound.MailAiMessages.AnalyzeContentRequest;
import com.workplace.mail.outbound.MailAiMessages.AnalyzeContentResult;
import com.workplace.mail.repository.EmailMessageRepository;
import com.workplace.mail.repository.EmailMessageRepository.AnalysisContext;
import com.workplace.mail.util.NewContentExtractor;
import com.workplace.mail.util.SingleFlight;
import java.time.Duration;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.util.StringUtils;

/**
 * 메일 AI 분석(WP-149) — ③ 원본 분석(원본별 1회 · 공통 비서 · 분류+객관 요약)과 ④ 개인 분석(사본별 1회 · 개인→공통 비서)을 수행하고 ⑤ 최종
 * 회신필요를 갱신한다.
 *
 * <p>LLM 호출은 트랜잭션 밖에서 하고 컨텍스트 조회·결과 저장만 짧은 트랜잭션({@code txTemplate}, @Primary
 * TenantAwareTransactionManager 라 RLS GUC 주입)으로 감싼다(#232). 같은 원본·사본을 동시에 분석하지 않도록 {@link
 * SingleFlight} 로 묶는다.
 */
@Slf4j
@Service
public class MailAnalysisService {

  /** 분류 허용 카테고리(미지 값은 null). ⚠️ 프론트 MailSidebar.CATEGORIES 와 값·순서 일치 유지 */
  static final Set<String> CATEGORIES = Set.of("업무", "개인", "알림", "프로모션", "뉴스레터");

  /** 요약 생략 기준 — 새 본문이 이 길이 이하면 요약하지 않는다(짧은 메일은 본문이 곧 요약). */
  public static final int SUMMARY_MIN_CHARS = 400;

  /** 단발 호출이라 turn 1 고정. */
  private static final int MAX_TURNS = 1;

  /** 다른 스레드가 같은 메일을 분석 중일 때 기다리는 상한 — LLM 타임아웃보다 넉넉히. */
  private static final Duration SINGLE_FLIGHT_WAIT = Duration.ofSeconds(150);

  private final AiAgentMailClient mailClient;
  private final EmailMessageRepository messageRepo;
  private final AssistantResolver assistantResolver;
  private final NeedsReplyFinalizer finalizer;
  private final TransactionTemplate txTemplate;
  private final SingleFlight singleFlight = new SingleFlight(SINGLE_FLIGHT_WAIT);

  public MailAnalysisService(
      AiAgentMailClient mailClient,
      EmailMessageRepository messageRepo,
      AssistantResolver assistantResolver,
      NeedsReplyFinalizer finalizer,
      PlatformTransactionManager txManager) {
    this.mailClient = mailClient;
    this.messageRepo = messageRepo;
    this.assistantResolver = assistantResolver;
    this.finalizer = finalizer;
    this.txTemplate = new TransactionTemplate(txManager);
  }

  /** 분석 컨텍스트(소유 검증 포함). 없으면 null. RLS GUC 주입 짧은 트랜잭션. */
  public AnalysisContext readContext(long userId, long messageId) {
    return txTemplate.execute(
        status -> messageRepo.findAnalysisContextByIdAndUser(userId, messageId).orElse(null));
  }

  /**
   * ③ 원본 분석 — 공통 비서가 있고 content 가 아직 분석되지 않았으면 분류(항상)와 객관 요약(새 본문 > 400자이고 자동 발송이 아닐 때)을 받는다. 자동
   * 발송이면 본문 대신 미리보기를 보낸다. 저장 후 같은 content 의 분석된 사본들의 ⑤ 를 재계산한다.
   *
   * <p>빈 본문은 LLM 을 부르지 않고 시도로도 기록하지 않는다(아직 미적재일 수 있음). LLM·파싱 실패는 예외를 그대로 던진다 — 시도 기록이 남지 않아 다음 백필
   * 대상이 되고, 백그라운드 호출자가 삼킨다. 읽음 여부는 보지 않는다 — 선제 호출부(본문 적재 직후·백필 대상 술어)가 안 읽은 메일만 고르고, 열람 시 요약 GET 은
   * 읽은 메일에도 이 메서드를 쓴다(판단 13).
   */
  public void analyzeContent(long userId, long messageId) {
    AnalysisContext pre = readContext(userId, messageId);
    if (!contentAnalyzable(pre)) {
      return;
    }
    AssistantSpec spec = assistantResolver.resolveWorkspaceOrEmpty().orElse(null);
    if (spec == null) {
      return; // 공통 비서 없음 — ④ 가 분류를 보충한다
    }
    singleFlight.run(
        contentKey(pre.contentId()), () -> runContentAnalysis(userId, messageId, spec));
  }

  private void runContentAnalysis(long userId, long messageId, AssistantSpec spec) {
    AnalysisContext ctx = readContext(userId, messageId); // 다른 실행을 기다렸다면 그 결과를 반영
    if (!contentAnalyzable(ctx)) {
      return;
    }
    String newBody = newBody(ctx);
    if (!StringUtils.hasText(newBody)) {
      return;
    }
    boolean skipSummary = ctx.autoGenerated() || newBody.length() <= SUMMARY_MIN_CHARS;
    AnalyzeContentResult r =
        mailClient.analyzeContent(
            contentRequest(ctx, bodyInput(ctx, newBody), true, !skipSummary, spec));
    String category = validCategory(r.category());
    String summary = skipSummary ? null : r.summary();
    txTemplate.executeWithoutResult(
        status -> {
          if (messageRepo.saveContentAnalysis(messageId, category, summary, skipSummary)) {
            finalizer.recomputeForContent(ctx.contentId());
          }
        });
  }

  /** ③ 대상: 적재·검증된 사본 + content 연결 + 미시도. */
  private static boolean contentAnalyzable(AnalysisContext ctx) {
    return ctx != null && ctx.fetched() && ctx.contentId() != null && !ctx.contentAttempted();
  }

  /** 새로 쓴 부분(인용·서명 제거, 상한 적용) — ③·④·요약 상태 판정이 같은 값을 쓰도록 한 곳에서만 계산한다. */
  static String newBody(AnalysisContext ctx) {
    return NewContentExtractor.extract(ctx.bodyText(), ctx.bodyHtml(), ctx.snippet());
  }

  /** ③ 요청 조립 — 선제 분석과 "AI 요약" 강제 생성(Task 7)이 함께 쓴다. */
  static AnalyzeContentRequest contentRequest(
      AnalysisContext ctx,
      String body,
      boolean includeCategory,
      boolean includeSummary,
      AssistantSpec spec) {
    return new AnalyzeContentRequest(
        nz(ctx.subject()),
        sender(ctx),
        body,
        ctx.autoGenerated(),
        includeCategory,
        includeSummary,
        spec.agentUserId(),
        spec.model(),
        MAX_TURNS,
        spec.timeoutMs());
  }

  /** 허용 카테고리만(미지 값·null → null). Set.of 는 contains(null) 에서 NPE 를 던지므로 null 을 먼저 거른다. */
  static String validCategory(String category) {
    return category != null && CATEGORIES.contains(category) ? category : null;
  }

  /** 자동 발송이면 미리보기(있을 때), 아니면 새 본문. */
  static String bodyInput(AnalysisContext ctx, String newBody) {
    return ctx.autoGenerated() && StringUtils.hasText(ctx.snippet()) ? ctx.snippet() : newBody;
  }

  /** "이름 <주소>" 또는 주소. */
  static String sender(AnalysisContext ctx) {
    String addr = nz(ctx.fromAddress());
    return StringUtils.hasText(ctx.fromName()) ? ctx.fromName() + " <" + addr + ">" : addr;
  }

  static String contentKey(long contentId) {
    return "content:" + contentId;
  }

  static String personalKey(long messageId) {
    return "personal:" + messageId;
  }

  static String nz(String s) {
    return s == null ? "" : s;
  }
}
