package com.workplace.mail.service;

import com.workplace.mail.repository.EmailMessageRepository;
import com.workplace.mail.repository.EmailMessageRepository.RuleRow;
import com.workplace.mail.repository.MailPeopleRepository;
import com.workplace.mail.util.NeedsReplyRules;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * ⑤ 최종 회신필요 저장(WP-149) — 저장된 raw·수신자·자동 발송·분류로 {@link NeedsReplyRules#finalValue} 를 계산해
 * ai_needs_reply 에 쓴다. ③·④ 중 늦게 끝난 쪽이 부른다(④ 는 자기 사본, ③ 은 같은 content 의 분석된 형제 사본 전부). 호출자 트랜잭션 안에서
 * 실행된다. "나" 주소는 ④ 와 같은 {@link MailPeopleRepository#listOwnAddresses}(계정 주소 + user.email, WP-150)를
 * 써서 실행 순서와 무관하게 같은 결과가 나온다.
 */
@Component
@RequiredArgsConstructor
public class NeedsReplyFinalizer {

  private final EmailMessageRepository messageRepo;
  private final MailPeopleRepository peopleRepo;

  /** 한 사본 재계산. raw 가 없으면(미분석·배포 전 분류) 그대로 둔다. */
  public void recompute(long messageId) {
    recompute(messageId, new HashMap<>());
  }

  /** content 를 공유하는 분석된 사본 전부 재계산 — 소유자별 "나" 주소는 한 번만 읽는다. */
  public void recomputeForContent(long contentId) {
    Map<Long, Set<String>> addressCache = new HashMap<>();
    for (Long id : messageRepo.listAnalyzedSiblingIds(contentId)) {
      recompute(id, addressCache);
    }
  }

  private void recompute(long messageId, Map<Long, Set<String>> addressCache) {
    RuleRow row = messageRepo.findRuleRow(messageId).orElse(null);
    if (row == null || row.raw() == null) {
      return;
    }
    Set<String> me =
        addressCache.computeIfAbsent(
            row.userId(), userId -> Set.copyOf(peopleRepo.listOwnAddresses(userId)));
    NeedsReplyRules.Input in =
        NeedsReplyRules.Input.of(
            row.fromAddress(),
            me,
            row.toAddresses(),
            row.ccAddresses(),
            row.autoGenerated(),
            row.category());
    messageRepo.updateFinalNeedsReply(messageId, NeedsReplyRules.finalValue(row.raw(), in));
  }
}
