package com.workplace.mail.outbound;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.header;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.jsonPath;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.method;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withServerError;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withStatus;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withSuccess;

import com.workplace.mail.exception.MailAiException;
import com.workplace.mail.exception.MailAiUnavailableException;
import com.workplace.mail.outbound.MailAiMessages.AnalyzeContentRequest;
import com.workplace.mail.outbound.MailAiMessages.AnalyzeContentResult;
import com.workplace.mail.outbound.MailAiMessages.AnalyzePersonalRequest;
import com.workplace.mail.outbound.MailAiMessages.AnalyzePersonalResult;
import com.workplace.mail.outbound.MailAiMessages.Me;
import com.workplace.mail.outbound.MailAiMessages.Recipient;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.test.web.client.MockRestServiceServer;
import org.springframework.web.client.RestClient;

class AiAgentMailClientTest {

  private RestClient.Builder builder;
  private MockRestServiceServer server;
  private AiAgentMailClient client;

  @BeforeEach
  void setUp() {
    builder = RestClient.builder().baseUrl("http://ai-agent.test");
    server = MockRestServiceServer.bindTo(builder).build();
    client = new AiAgentMailClient(builder, "tok-123");
  }

  @Test
  void 서버오류_무재시도_MailAiException() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-content"))
        .andRespond(withServerError());
    assertThatThrownBy(
            () ->
                client.analyzeContent(
                    new AnalyzeContentRequest(
                        "s", "a@b", "x", false, true, false, 5L, "m", 1, 60000)))
        .isInstanceOf(MailAiException.class);
    server.verify();
  }

  @Test
  void _503_은_MailAiUnavailableException() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-content"))
        .andRespond(
            withStatus(HttpStatus.SERVICE_UNAVAILABLE)
                .body("{}")
                .contentType(MediaType.APPLICATION_JSON));
    assertThatThrownBy(
            () ->
                client.analyzeContent(
                    new AnalyzeContentRequest(
                        "s", "a@b", "x", false, true, false, 5L, "m", 1, 60000)))
        .isInstanceOf(MailAiUnavailableException.class);
    server.verify();
  }

  @Test
  void 원본분석_정상_역직렬화() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-content"))
        .andExpect(method(HttpMethod.POST))
        .andExpect(header(HttpHeaders.AUTHORIZATION, "Internal tok-123"))
        .andExpect(jsonPath("$.includeSummary").value(false))
        .andExpect(jsonPath("$.autoGenerated").value(true))
        .andRespond(
            withSuccess("{\"category\":\"알림\",\"summary\":null}", MediaType.APPLICATION_JSON));

    AnalyzeContentResult r =
        client.analyzeContent(
            new AnalyzeContentRequest("s", "a@b", "x", true, true, false, 5L, "m", 1, 60000));
    assertThat(r.category()).isEqualTo("알림");
    assertThat(r.summary()).isNull();
    server.verify();
  }

  @Test
  void 개인분석_정상_역직렬화() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-personal"))
        .andExpect(method(HttpMethod.POST))
        .andExpect(jsonPath("$.recipient.myRole").value("CC"))
        .andExpect(jsonPath("$.me.addresses[0]").value("me@x.com"))
        .andRespond(
            withSuccess(
                "{\"needsReply\":true,\"personalSummary\":null,\"personalSummaryValid\":true,\"category\":null}",
                MediaType.APPLICATION_JSON));

    AnalyzePersonalResult r =
        client.analyzePersonal(
            new AnalyzePersonalRequest(
                "s",
                "a@b.com",
                "",
                "x",
                false,
                new Me(List.of("me@x.com")),
                new Recipient("CC", 1, 1),
                true,
                true,
                false,
                5L,
                "m",
                1,
                60000));
    assertThat(r.needsReply()).isTrue();
    assertThat(r.personalSummaryValid()).isTrue();
    server.verify();
  }
}
