package com.workplace.mail.outbound;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.header;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.jsonPath;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.method;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withServerError;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withStatus;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withSuccess;

import com.workplace.mail.exception.MailAiException;
import com.workplace.mail.exception.MailAiUnavailableException;
import com.workplace.mail.outbound.MailAiMessages.AnalyzeContentRequest;
import com.workplace.mail.outbound.MailAiMessages.AnalyzeContentResult;
import com.workplace.mail.outbound.MailAiMessages.AnalyzePersonalRequest;
import com.workplace.mail.outbound.MailAiMessages.AnalyzePersonalResult;
import com.workplace.mail.outbound.MailAiMessages.IssueRef;
import com.workplace.mail.outbound.MailAiMessages.Me;
import com.workplace.mail.outbound.MailAiMessages.PriorMail;
import com.workplace.mail.outbound.MailAiMessages.Recipient;
import com.workplace.mail.outbound.MailAiMessages.Sender;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.test.web.client.MockRestServiceServer;
import org.springframework.web.client.RestClient;

class AiAgentMailClientTest {

  private RestClient.Builder builder;
  private MockRestServiceServer server;
  private AiAgentMailClient client;

  @BeforeEach
  void setUp() {
    builder = RestClient.builder().baseUrl("http://ai-agent.test");
    server = MockRestServiceServer.bindTo(builder).build();
    client = new AiAgentMailClient(builder, "tok-123");
  }

  @Test
  void 서버오류_무재시도_MailAiException() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-content"))
        .andRespond(withServerError());
    assertThatThrownBy(
            () ->
                client.analyzeContent(
                    new AnalyzeContentRequest(
                        "s", "a@b", "x", false, true, false, 5L, "m", 1, 60000)))
        .isInstanceOf(MailAiException.class);
    server.verify();
  }

  @Test
  void _503_은_MailAiUnavailableException() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-content"))
        .andRespond(
            withStatus(HttpStatus.SERVICE_UNAVAILABLE)
                .body("{}")
                .contentType(MediaType.APPLICATION_JSON));
    assertThatThrownBy(
            () ->
                client.analyzeContent(
                    new AnalyzeContentRequest(
                        "s", "a@b", "x", false, true, false, 5L, "m", 1, 60000)))
        .isInstanceOf(MailAiUnavailableException.class);
    server.verify();
  }

  @Test
  void 원본분석_정상_역직렬화() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-content"))
        .andExpect(method(HttpMethod.POST))
        .andExpect(header(HttpHeaders.AUTHORIZATION, "Internal tok-123"))
        .andExpect(jsonPath("$.includeSummary").value(false))
        .andExpect(jsonPath("$.autoGenerated").value(true))
        .andRespond(
            withSuccess("{\"category\":\"알림\",\"summary\":null}", MediaType.APPLICATION_JSON));

    AnalyzeContentResult r =
        client.analyzeContent(
            new AnalyzeContentRequest("s", "a@b", "x", true, true, false, 5L, "m", 1, 60000));
    assertThat(r.category()).isEqualTo("알림");
    assertThat(r.summary()).isNull();
    server.verify();
  }

  @Test
  void 개인분석_정상_역직렬화() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-personal"))
        .andExpect(method(HttpMethod.POST))
        .andExpect(jsonPath("$.recipient.myRole").value("CC"))
        .andExpect(jsonPath("$.me.addresses[0]").value("me@x.com"))
        .andExpect(jsonPath("$.me.name").value("홍길동"))
        .andExpect(jsonPath("$.me.groups[0]").value("개발팀"))
        .andRespond(
            withSuccess(
                "{\"needsReply\":true,\"personalSummary\":null,\"personalSummaryValid\":true,\"category\":null}",
                MediaType.APPLICATION_JSON));

    AnalyzePersonalResult r =
        client.analyzePersonal(
            new AnalyzePersonalRequest(
                "s",
                "a@b.com",
                "",
                "x",
                false,
                new Me(List.of("me@x.com"), "홍길동", List.of(), "팀장", List.of("개발팀")),
                new Recipient("CC", 1, 1),
                null,
                List.of(),
                null,
                List.of(),
                true,
                true,
                false,
                5L,
                "m",
                1,
                60000));
    assertThat(r.needsReply()).isTrue();
    assertThat(r.personalSummaryValid()).isTrue();
    server.verify();
  }

  /**
   * WP-150 보강 블록(sender·thread·linkedIssue·attachments)의 JSON 경로·값을 ai-agent zod 스키마
   * (analyzePersonalSchema)와 같게 고정한다. zod 는 형식이 틀린 블록을 조용히 버리므로(.catch), 필드 이름이 바뀌어도 400 없이 블록만
   * 사라진다 — 이 테스트가 그 회귀를 잡는다.
   */
  @Test
  void 개인분석_보강블록_JSON_형식이_zod_스키마와_일치() {
    server
        .expect(requestTo("http://ai-agent.test/mail/analyze-personal"))
        // 최상위 필드
        .andExpect(jsonPath("$.subject").value("제목"))
        .andExpect(jsonPath("$.fromAddress").value("kim@x.com"))
        .andExpect(jsonPath("$.fromName").value("김철수"))
        .andExpect(jsonPath("$.body").value("본문"))
        .andExpect(jsonPath("$.autoGenerated").value(false))
        .andExpect(jsonPath("$.includeNeedsReply").value(true))
        .andExpect(jsonPath("$.includePersonalSummary").value(false))
        .andExpect(jsonPath("$.includeCategory").value(true))
        .andExpect(jsonPath("$.assistantAgentId").value(5))
        .andExpect(jsonPath("$.model").value("m"))
        .andExpect(jsonPath("$.maxTurns").value(1))
        .andExpect(jsonPath("$.timeoutMs").value(60000))
        // me
        .andExpect(jsonPath("$.me.addresses[0]").value("me@x.com"))
        .andExpect(jsonPath("$.me.name").value("홍길동"))
        .andExpect(jsonPath("$.me.otherNames[0]").value("길동"))
        .andExpect(jsonPath("$.me.title").value("팀장"))
        .andExpect(jsonPath("$.me.groups[0]").value("개발팀"))
        // recipient
        .andExpect(jsonPath("$.recipient.myRole").value("TO"))
        .andExpect(jsonPath("$.recipient.toCount").value(2))
        .andExpect(jsonPath("$.recipient.ccCount").value(3))
        // sender
        .andExpect(jsonPath("$.sender.relation").value("MEMBER"))
        .andExpect(jsonPath("$.sender.name").value("김철수"))
        .andExpect(jsonPath("$.sender.title").value("과장"))
        .andExpect(jsonPath("$.sender.organization").value("영업팀"))
        .andExpect(jsonPath("$.sender.sameGroups[0]").value("개발팀"))
        .andExpect(jsonPath("$.sender.favorite").value(true))
        // thread
        .andExpect(jsonPath("$.thread[0].fromMe").value(true))
        .andExpect(jsonPath("$.thread[0].from").value("홍길동 <me@x.com>"))
        .andExpect(jsonPath("$.thread[0].date").value("2026-09-30T01:02:03Z"))
        .andExpect(jsonPath("$.thread[0].body").value("이전 본문"))
        // linkedIssue
        .andExpect(jsonPath("$.linkedIssue.key").value("WP-9"))
        .andExpect(jsonPath("$.linkedIssue.title").value("연결 이슈"))
        .andExpect(jsonPath("$.linkedIssue.status").value("IN_PROGRESS"))
        // attachments
        .andExpect(jsonPath("$.attachments[0]").value("견적서.pdf"))
        .andRespond(
            withSuccess(
                "{\"needsReply\":false,\"personalSummary\":null,\"personalSummaryValid\":false,\"category\":null}",
                MediaType.APPLICATION_JSON));

    client.analyzePersonal(
        new AnalyzePersonalRequest(
            "제목",
            "kim@x.com",
            "김철수",
            "본문",
            false,
            new Me(List.of("me@x.com"), "홍길동", List.of("길동"), "팀장", List.of("개발팀")),
            new Recipient("TO", 2, 3),
            new Sender("MEMBER", "김철수", "과장", "영업팀", List.of("개발팀"), true),
            List.of(new PriorMail(true, "홍길동 <me@x.com>", "2026-09-30T01:02:03Z", "이전 본문")),
            new IssueRef("WP-9", "연결 이슈", "IN_PROGRESS"),
            List.of("견적서.pdf"),
            true,
            false,
            true,
            5L,
            "m",
            1,
            60000));
    server.verify();
  }
}
