package com.workplace.mail;

import static com.workplace.jooq.Tables.EMAIL_CONTENT;
import static com.workplace.jooq.Tables.EMAIL_MESSAGE;
import static org.assertj.core.api.Assertions.assertThat;

import com.icegreen.greenmail.configuration.GreenMailConfiguration;
import com.icegreen.greenmail.junit5.GreenMailExtension;
import com.workplace.auth.service.AssistantResolver;
import com.workplace.global.security.EncryptionService;
import com.workplace.mail.dto.BodyTarget;
import com.workplace.mail.outbound.AiAgentMailClient;
import com.workplace.mail.repository.EmailAccountRepository;
import com.workplace.mail.repository.EmailMessageRepository;
import com.workplace.mail.service.MailBodyFetcher;
import com.workplace.mail.service.MailSyncService;
import com.workplace.support.IntegrationTestBase;
import com.workplace.support.TestFixtures;
import org.jooq.DSLContext;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.annotation.Transactional;

/**
 * MailBodyFetcher 통합 테스트 — GreenMail(MailTestPorts.IMAP)에서 단건 본문을 적재해 캐시(body_fetched_at)·본문을 검증한다.
 *
 * <p>sync 는 메타만 저장하므로 본문/스니펫은 적재 전 null 이고 body_fetched_at 도 null 이다. 따라서 sync 직후가 곧 '미적재' 상태이며,
 * fetchBody 가 실제로 본문을 내려받아 채우는지(그리고 멱등/분류) 를 그대로 검증할 수 있다.
 */
@Transactional
class MailBodyFetcherTest extends IntegrationTestBase {

  @RegisterExtension
  static GreenMailExtension greenMail =
      new GreenMailExtension(MailTestPorts.SMTP_IMAP)
          .withConfiguration(
              GreenMailConfiguration.aConfig().withUser("box@test.local", "box@test.local", "pw"));

  @Autowired DSLContext dsl;
  @Autowired MailSyncService syncService;
  @Autowired MailBodyFetcher bodyFetcher;
  @Autowired EmailAccountRepository accountRepo;
  @Autowired EmailMessageRepository messageRepo;
  @Autowired EncryptionService encryption;

  /** ai-agent 실호출 차단. */
  @MockitoBean AiAgentMailClient mailClient;

  /** 비서 해석 — 본문 적재 경로는 비서를 보지 않는다(WP-149). 컨텍스트 공유용 mock. */
  @MockitoBean AssistantResolver assistantResolver;

  @Test
  void fetchBody_본문적재_및_캐시() {
    long user = TestFixtures.createHuman(dsl);
    long accountId = MailTestSupport.insertAccount(accountRepo, encryption, user, false);
    MailTestPorts.sendText("box@test.local", "alice@example.com", "제목", "본문입니다");
    greenMail.waitForIncomingEmail(1);

    syncService.sync(user, accountId);
    long messageId = messageRepo.listMissingBody(accountId, 10).get(0).messageId();

    assertThat(
            bodyFetcher.fetchBody(
                user, messageRepo.findBodyTarget(accountId, messageId).orElseThrow()))
        .isTrue();

    BodyTarget after = messageRepo.findBodyTarget(accountId, messageId).orElseThrow();
    // Task5: bodyFetchedAt 은 email_content.body_fetched_at 기준
    assertThat(after.bodyFetchedAt()).isNotNull();
    // Task5: 본문은 email_content 에 기록됨 — envelope JOIN content 로 검증(Task6 이전까지 reader 미이관)
    String bodyViaContent =
        dsl.select(EMAIL_CONTENT.BODY_TEXT)
            .from(EMAIL_MESSAGE)
            .join(EMAIL_CONTENT)
            .on(EMAIL_CONTENT.ID.eq(EMAIL_MESSAGE.CONTENT_ID))
            .where(EMAIL_MESSAGE.ID.eq(messageId))
            .fetchOneInto(String.class);
    assertThat(bodyViaContent).contains("본문입니다");
  }

  /** 이미 적재된 대상(body_fetched_at != null)은 no-op — IMAP 미접속. */
  @Test
  void fetchBody_이미적재면_noop() {
    long user = TestFixtures.createHuman(dsl);
    long accountId = MailTestSupport.insertAccount(accountRepo, encryption, user, false);
    MailTestPorts.sendText("box@test.local", "alice@example.com", "제목", "본문입니다");
    greenMail.waitForIncomingEmail(1);

    syncService.sync(user, accountId);
    long messageId = messageRepo.listMissingBody(accountId, 10).get(0).messageId();
    // 1차 적재로 body_fetched_at 채움
    bodyFetcher.fetchBody(user, messageRepo.findBodyTarget(accountId, messageId).orElseThrow());
    BodyTarget loaded = messageRepo.findBodyTarget(accountId, messageId).orElseThrow();
    assertThat(loaded.bodyFetchedAt()).isNotNull();

    // 2차 호출은 가드로 즉시 return — 예외 없이 멱등
    assertThat(bodyFetcher.fetchBody(user, loaded)).isFalse(); // 가드로 즉시 false — 적재·분석 없음
  }

  /** WP-149 ②: List-Unsubscribe 헤더가 있는 IMAP 메일은 본문 적재 시 content.auto_generated=true 로 기록된다. */
  @Test
  void fetchBody_listUnsubscribe_marksAutoGenerated() {
    long user = TestFixtures.createHuman(dsl);
    long accountId = MailTestSupport.insertAccount(accountRepo, encryption, user, false);
    MailTestPorts.sendWithHeader(
        "box@test.local",
        "news@example.com",
        "뉴스레터",
        "이번 주 소식",
        "List-Unsubscribe",
        "<mailto:unsub@example.com>");
    greenMail.waitForIncomingEmail(1);

    syncService.sync(user, accountId);
    long messageId = messageRepo.listMissingBody(accountId, 10).get(0).messageId();
    bodyFetcher.fetchBody(user, messageRepo.findBodyTarget(accountId, messageId).orElseThrow());

    Boolean auto =
        dsl.select(EMAIL_CONTENT.AUTO_GENERATED)
            .from(EMAIL_MESSAGE)
            .join(EMAIL_CONTENT)
            .on(EMAIL_CONTENT.ID.eq(EMAIL_MESSAGE.CONTENT_ID))
            .where(EMAIL_MESSAGE.ID.eq(messageId))
            .fetchOneInto(Boolean.class);
    assertThat(auto).isTrue();
  }
}
