import { describe, expect, it } from 'vitest'

import { PREVIEW_SCROLLBAR_STYLE, withPreviewScrollbar } from './htmlPreviewDoc'

describe('withPreviewScrollbar', () => {
  it('DOCTYPE 이 있으면 그 뒤에 주입해 표준 모드를 유지한다', () => {
    const html = '<!DOCTYPE html><html><body>본문</body></html>'
    const out = withPreviewScrollbar(html)
    expect(out.startsWith('<!DOCTYPE html>' + PREVIEW_SCROLLBAR_STYLE)).toBe(true)
    expect(out.endsWith('<html><body>본문</body></html>')).toBe(true)
  })

  it('BOM·공백·소문자 DOCTYPE 도 인식한다', () => {
    const html = '\uFEFF\n  <!doctype html>\n<p>x</p>'
    expect(withPreviewScrollbar(html)).toBe('\uFEFF\n  <!doctype html>' + PREVIEW_SCROLLBAR_STYLE + '\n<p>x</p>')
  })

  it('DOCTYPE 앞의 주석·XML 선언은 건너뛰고 DOCTYPE 뒤에 주입한다', () => {
    const commented = '<!-- generated by X -->\n<!DOCTYPE html><p>x</p>'
    expect(withPreviewScrollbar(commented)).toBe(
      '<!-- generated by X -->\n<!DOCTYPE html>' + PREVIEW_SCROLLBAR_STYLE + '<p>x</p>',
    )
    const xhtml = '<?xml version="1.0"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0//EN"><html/>'
    expect(withPreviewScrollbar(xhtml)).toBe(
      '<?xml version="1.0"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0//EN">' + PREVIEW_SCROLLBAR_STYLE + '<html/>',
    )
  })

  it('앞 공백이 길고 DOCTYPE 이 없어도 즉시 끝난다(지수 백트래킹 회귀 가드)', () => {
    const html = '\n'.repeat(5000) + '<p>조각</p>'
    const t0 = performance.now()
    expect(withPreviewScrollbar(html)).toBe(PREVIEW_SCROLLBAR_STYLE + html)
    expect(performance.now() - t0).toBeLessThan(100)
  })

  it('DOCTYPE 이 없으면 맨 앞에 주입한다', () => {
    expect(withPreviewScrollbar('<p>조각</p>')).toBe(PREVIEW_SCROLLBAR_STYLE + '<p>조각</p>')
  })

  it('본문 중간의 doctype 문자열은 건드리지 않는다', () => {
    const html = '<p>예: <!DOCTYPE html></p>'
    expect(withPreviewScrollbar(html)).toBe(PREVIEW_SCROLLBAR_STYLE + html)
  })

  it('주입 내용은 스타일뿐이다(스크립트 없음)', () => {
    expect(PREVIEW_SCROLLBAR_STYLE).not.toMatch(/<script/i)
    expect(PREVIEW_SCROLLBAR_STYLE).toContain('*{scrollbar-width:thin}')
    // 상속되는 색은 :root 에만 — 문서가 body 등에 준 scrollbar-color 상속을 끊지 않는다.
    expect(PREVIEW_SCROLLBAR_STYLE).not.toMatch(/\*\{[^}]*scrollbar-color/)
  })
})
