import { describe, expect, it } from 'vitest'

import { THIN_SCROLLBAR_STYLE, withThinScrollbar } from './sandboxedHtml'

describe('withThinScrollbar', () => {
  it('DOCTYPE 이 있으면 그 뒤에 주입해 표준 모드를 유지한다', () => {
    const html = '<!DOCTYPE html><html><body>본문</body></html>'
    const out = withThinScrollbar(html)
    expect(out.startsWith('<!DOCTYPE html>' + THIN_SCROLLBAR_STYLE)).toBe(true)
    expect(out.endsWith('<html><body>본문</body></html>')).toBe(true)
  })

  it('BOM·공백·소문자 DOCTYPE 도 인식한다', () => {
    const html = '\uFEFF\n  <!doctype html>\n<p>x</p>'
    expect(withThinScrollbar(html)).toBe('\uFEFF\n  <!doctype html>' + THIN_SCROLLBAR_STYLE + '\n<p>x</p>')
  })

  it('DOCTYPE 앞의 주석·XML 선언은 건너뛰고 DOCTYPE 뒤에 주입한다', () => {
    const commented = '<!-- generated by X -->\n<!DOCTYPE html><p>x</p>'
    expect(withThinScrollbar(commented)).toBe(
      '<!-- generated by X -->\n<!DOCTYPE html>' + THIN_SCROLLBAR_STYLE + '<p>x</p>',
    )
    const xhtml = '<?xml version="1.0"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0//EN"><html/>'
    expect(withThinScrollbar(xhtml)).toBe(
      '<?xml version="1.0"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0//EN">' + THIN_SCROLLBAR_STYLE + '<html/>',
    )
  })

  it('앞 공백이 길고 DOCTYPE 이 없어도 즉시 끝난다(지수 백트래킹 회귀 가드)', () => {
    const html = '\n'.repeat(5000) + '<p>조각</p>'
    const t0 = performance.now()
    expect(withThinScrollbar(html)).toBe(THIN_SCROLLBAR_STYLE + html)
    expect(performance.now() - t0).toBeLessThan(100)
  })

  it('주석이 길게 이어지고 DOCTYPE 이 없어도 즉시 끝난다(지수 백트래킹 회귀 가드)', () => {
    const html = '<!---->'.repeat(2000) + '<!--a-->'.repeat(2000) + '<p>메일</p>'
    const t0 = performance.now()
    expect(withThinScrollbar(html)).toBe(THIN_SCROLLBAR_STYLE + html)
    expect(performance.now() - t0).toBeLessThan(100)
  })

  it('주석이 여러 개 앞서도 그 뒤 DOCTYPE 을 찾는다', () => {
    const html = '<!--a--> <!--b-->\n<!doctype html><p>x</p>'
    expect(withThinScrollbar(html)).toBe('<!--a--> <!--b-->\n<!doctype html>' + THIN_SCROLLBAR_STYLE + '<p>x</p>')
  })

  it('닫히지 않은 주석·DOCTYPE 이면 맨 앞에 주입한다', () => {
    expect(withThinScrollbar('<!-- 열림만')).toBe(THIN_SCROLLBAR_STYLE + '<!-- 열림만')
    expect(withThinScrollbar('<!DOCTYPE html')).toBe(THIN_SCROLLBAR_STYLE + '<!DOCTYPE html')
  })

  it('DOCTYPE 이 없으면 맨 앞에 주입한다', () => {
    expect(withThinScrollbar('<p>조각</p>')).toBe(THIN_SCROLLBAR_STYLE + '<p>조각</p>')
  })

  it('본문 중간의 doctype 문자열은 건드리지 않는다', () => {
    const html = '<p>예: <!DOCTYPE html></p>'
    expect(withThinScrollbar(html)).toBe(THIN_SCROLLBAR_STYLE + html)
  })

  it('주입 내용은 스타일뿐이다(스크립트 없음)', () => {
    expect(THIN_SCROLLBAR_STYLE).not.toMatch(/<script/i)
    expect(THIN_SCROLLBAR_STYLE).toContain('*{scrollbar-width:thin}')
    // 상속되는 색은 :root 에만 — 문서가 body 등에 준 scrollbar-color 상속을 끊지 않는다.
    expect(THIN_SCROLLBAR_STYLE).not.toMatch(/\*\{[^}]*scrollbar-color/)
  })
})
