package com.workplace.mail.util;

import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.function.Function;

/**
 * 메일 헤더로 대량·자동 발송 여부(email_content.auto_generated)를 판정한다(WP-149 ②, LLM 없음).
 *
 * <p>메일링리스트·뉴스레터·자동 응답은 사람이 답장할 대상이 아니므로 ⑤ 회신필요 규칙과 요약 생략의 근거로 쓴다. 헤더 원문은 저장하지 않고 판정 결과만 남긴다.
 * IMAP(jakarta.mail)·Graph(internetMessageHeaders) 가 헤더를 읽는 방식이 달라 조회 함수를 받는다.
 */
public final class AutoGeneratedHeaders {

  /** 대량 발송을 뜻하는 Precedence 값. */
  private static final Set<String> BULK_PRECEDENCE = Set.of("bulk", "list", "junk");

  private AutoGeneratedHeaders() {}

  /**
   * 자동 발송 여부. 아래 중 하나라도 있으면 true.
   *
   * <ul>
   *   <li>{@code List-Unsubscribe}·{@code List-Id}·{@code X-Auto-Response-Suppress} 값이 비어 있지 않음
   *   <li>{@code Precedence} 가 bulk·list·junk
   *   <li>{@code Auto-Submitted} 가 비어 있지 않고 {@code no} 가 아님
   * </ul>
   *
   * @param valuesOf 헤더 이름(대소문자 무시) → 값 목록. 헤더가 없으면 빈 목록
   */
  public static boolean detect(Function<String, List<String>> valuesOf) {
    if (hasValue(valuesOf.apply("List-Unsubscribe"))
        || hasValue(valuesOf.apply("List-Id"))
        || hasValue(valuesOf.apply("X-Auto-Response-Suppress"))) {
      return true;
    }
    for (String v : valuesOf.apply("Precedence")) {
      if (v != null && BULK_PRECEDENCE.contains(v.trim().toLowerCase(Locale.ROOT))) {
        return true;
      }
    }
    for (String v : valuesOf.apply("Auto-Submitted")) {
      // "auto-notified; owner-email=..." 처럼 파라미터가 붙을 수 있어 첫 토큰만 본다. "no" 는 사람이 보낸 메일이라는 명시다.
      String token = v == null ? "" : v.split(";", 2)[0].trim();
      if (!token.isEmpty() && !token.equalsIgnoreCase("no")) {
        return true;
      }
    }
    return false;
  }

  /** 값 목록 중 공백이 아닌 값이 하나라도 있는지. */
  private static boolean hasValue(List<String> values) {
    return values.stream().anyMatch(v -> v != null && !v.isBlank());
  }
}
