package com.workplace.mail.util;

import java.util.List;
import java.util.Set;

/**
 * ⑤ 최종 회신필요 판정(WP-149) — LLM 없이 규칙만으로 LLM 원판정(raw)의 true 를 false 로 바로잡는 최종 안전장치.
 *
 * <p>정확도 우선: 확실히 답장 대상이 아닌 경우(나 자신이 보냄·자동 발신자·대량 발송·나에게 온 메일 아님·알림성 분류)만 false 로 확정한다. CC 로만 받은 메일은
 * 규칙으로 막지 않고 LLM 판정을 따른다. 입력이 비어 판단할 수 없는 규칙은 건너뛴다(데이터 부재로 모든 메일을 false 로 만들지 않기 위해). ③·④ 실행 순서와
 * 무관하게 같은 결과가 나오도록 저장된 값만으로 계산한다.
 */
public final class NeedsReplyRules {

  /** 자동 발신자 로컬파트(확실한 것만). "+태그"는 떼고 비교한다. 테스트로 목록을 고정한다. */
  public static final Set<String> AUTO_LOCAL_PARTS =
      Set.of(
          "noreply",
          "no-reply",
          "donotreply",
          "do-not-reply",
          "mailer-daemon",
          "postmaster",
          "bounce",
          "bounces");

  /** 답장 대상이 아닌 분류. */
  public static final Set<String> NON_REPLY_CATEGORIES = Set.of("알림", "프로모션", "뉴스레터");

  /** 받는 사람 목록에서 나의 위치(프롬프트 "[받는 사람]" 블록용). UNKNOWN = To·CC 모두 비어 판단 불가. */
  public enum RecipientRole {
    TO,
    CC,
    NONE,
    UNKNOWN
  }

  /**
   * 규칙 입력. 주소는 모두 소문자.
   *
   * @param myAddresses "나"의 주소들(WP-149: 사용자의 모든 메일 계정 주소, WP-150: "나" 프로필 전체)
   * @param category content 분류(없으면 null — category 조건 생략)
   */
  public record Input(
      String fromAddress,
      Set<String> myAddresses,
      List<String> to,
      List<String> cc,
      boolean autoGenerated,
      String category) {

    /** 저장된 헤더 문자열로 만든다(파싱·정규화 포함 — 보낸 사람·받는 사람·"나" 주소 모두 소문자로). */
    public static Input of(
        String fromAddress,
        Set<String> myAddresses,
        String toHeader,
        String ccHeader,
        boolean autoGenerated,
        String category) {
      return new Input(
          MailAddresses.normalize(fromAddress),
          // 호출부 대소문자·null 에 기대지 않도록 "나" 주소도 여기서 정규화한다
          myAddresses == null
              ? Set.of()
              : myAddresses.stream()
                  .map(MailAddresses::normalize)
                  .filter(java.util.Objects::nonNull)
                  .collect(java.util.stream.Collectors.toUnmodifiableSet()),
          MailAddresses.parseList(toHeader),
          MailAddresses.parseList(ccHeader),
          autoGenerated,
          category);
    }
  }

  private NeedsReplyRules() {}

  /** 분류와 무관한 확정 false 규칙에 걸리는지 — ④ 개인 요약 생략 판단에도 쓴다. */
  public static boolean blockedByRules(Input in) {
    return isSelf(in) || isAutoSender(in.fromAddress()) || in.autoGenerated() || notAddressed(in);
  }

  /** 분류가 알림·프로모션·뉴스레터인지. 분류가 없으면 false(조건 생략). */
  public static boolean blockedByCategory(String category) {
    return category != null && NON_REPLY_CATEGORIES.contains(category);
  }

  /** 최종값. raw 가 없으면(미분석·LLM 실패) null — 호출자는 저장값을 건드리지 않는다. */
  public static Boolean finalValue(Boolean raw, Input in) {
    if (raw == null) {
      return null;
    }
    return raw && !blockedByRules(in) && !blockedByCategory(in.category());
  }

  /** To/CC 에서 나의 위치. */
  public static RecipientRole recipientRole(Input in) {
    if (in.to().isEmpty() && in.cc().isEmpty()) {
      return RecipientRole.UNKNOWN;
    }
    if (in.to().stream().anyMatch(in.myAddresses()::contains)) {
      return RecipientRole.TO;
    }
    if (in.cc().stream().anyMatch(in.myAddresses()::contains)) {
      return RecipientRole.CC;
    }
    return RecipientRole.NONE;
  }

  /** 보낸 사람이 나 자신. */
  private static boolean isSelf(Input in) {
    return in.fromAddress() != null && in.myAddresses().contains(in.fromAddress());
  }

  /** 자동 발신자 로컬파트. */
  static boolean isAutoSender(String from) {
    if (from == null) {
      return false;
    }
    int at = from.indexOf('@');
    String local = at < 0 ? from : from.substring(0, at);
    int plus = local.indexOf('+');
    if (plus >= 0) {
      local = local.substring(0, plus);
    }
    return AUTO_LOCAL_PARTS.contains(local);
  }

  /** 내 주소가 To 에도 CC 에도 없음. 받는 사람이나 내 주소를 모르면 판단하지 않는다(false). */
  private static boolean notAddressed(Input in) {
    if (in.myAddresses().isEmpty()) {
      return false;
    }
    return recipientRole(in) == RecipientRole.NONE;
  }
}
