import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('./sdk-runner.js', () => ({
  runSdkCollect: vi.fn(),
}));

import {
  buildContentUserMessage,
  buildPersonalUserMessage,
  runMailAnalyzeContent,
  runMailAnalyzePersonal,
  runMailClassify,
  runMailSummarize,
  runMailReplyDraft,
  runMailDraftCoaching,
} from './run-mail-ai.js';
import { runSdkCollect } from './sdk-runner.js';

const fakeClient = { getProviderCredential: vi.fn() } as never;
const cfg = { assistantAgentId: 7, model: 'claude-sonnet-4-6', maxTurns: 1, timeoutMs: 60_000 };

beforeEach(() => {
  vi.clearAllMocks();
  (fakeClient as { getProviderCredential: ReturnType<typeof vi.fn> }).getProviderCredential =
    vi.fn().mockResolvedValue({ provider: 'anthropic', token: 'tok', model: null });
});

describe('runMailClassify', () => {
  it('분류 JSON 결과 반환 + 비서 토큰 fetch', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '{"category":"업무","needsReply":true}' }),
    ]);
    const out = await runMailClassify({ ...cfg, subject: '회의', from: 'a@b', snippet: '내일 2시' }, { client: fakeClient });
    expect(out).toEqual({ category: '업무', needsReply: true });
    expect((fakeClient as { getProviderCredential: ReturnType<typeof vi.fn> }).getProviderCredential).toHaveBeenCalledWith(7);
  });

  it('모델 결정: cfg.model(요청 body)이 credential.model 보다 우선한다', async () => {
    (fakeClient as { getProviderCredential: ReturnType<typeof vi.fn> }).getProviderCredential =
      vi.fn().mockResolvedValue({ provider: 'anthropic', token: 'tok', model: 'claude-opus-4-1' });
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '{"category":"업무","needsReply":true}' }),
    ]);
    await runMailClassify({ ...cfg, subject: '회의', from: 'a@b', snippet: '내일 2시' }, { client: fakeClient });
    const arg = vi.mocked(runSdkCollect).mock.calls[0][0];
    expect(arg.model).toBe('claude-sonnet-4-6'); // cfg.model 그대로(body 우선)
  });
});

describe('runMailSummarize', () => {
  it('요약 텍스트 반환', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '• 핵심' }),
    ]);
    const out = await runMailSummarize({ ...cfg, subject: 's', from: 'a@b', body: '본문' }, { client: fakeClient });
    expect(out).toEqual({ summary: '• 핵심' });
  });
});

describe('runMailReplyDraft', () => {
  it('답장 본문 반환 + 실패 시 temp 정리', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '안녕하세요, …' }),
    ]);
    const out = await runMailReplyDraft({ ...cfg, replyingAs: 'me@x', thread: [{ from: 'a@b', date: 'd', body: '원문' }] }, { client: fakeClient });
    expect(out.draftBody).toContain('안녕하세요');
  });
});

describe('runMailDraftCoaching', () => {
  it('코칭 JSON 파싱 결과 반환', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({
        type: 'result',
        subtype: 'success',
        result: '{"notes":[{"dimension":"TONE","message":"명령조"}],"improvedBodyHtml":"<p>개선</p>"}',
      }),
    ]);
    const out = await runMailDraftCoaching(
      { ...cfg, replyingAs: 'me@x', draftBody: '빨리 보내', thread: [] },
      { client: fakeClient },
    );
    expect(out.notes).toEqual([{ dimension: 'TONE', message: '명령조' }]);
    expect(out.improvedBodyHtml).toBe('<p>개선</p>');
  });
});

describe('buildContentUserMessage', () => {
  it('제목·보낸 사람·본문 블록', () => {
    expect(
      buildContentUserMessage({ ...cfg, subject: '배포', from: '김민수 <m@a.com>', body: '확인 부탁', autoGenerated: false, includeCategory: true, includeSummary: true }),
    ).toBe('[제목] 배포\n[보낸 사람] 김민수 <m@a.com>\n[본문]\n확인 부탁');
  });
  it('자동 발송이면 표시를 붙인다', () => {
    expect(
      buildContentUserMessage({ ...cfg, subject: 's', from: 'n@x.com', body: '미리보기', autoGenerated: true, includeCategory: true, includeSummary: false }),
    ).toContain('[자동 발송] 예');
  });
});

describe('buildPersonalUserMessage', () => {
  const base = {
    ...cfg,
    subject: '배포 일정 확인 부탁드립니다',
    fromAddress: 'minsu@acme.com',
    fromName: '김민수',
    body: '금요일까지 확인 부탁드립니다',
    autoGenerated: false,
    me: { addresses: ['gd@acme.com', 'gd@gmail.com'] },
    recipient: { myRole: 'TO' as const, toCount: 1, ccCount: 3 },
    includeNeedsReply: true,
    includePersonalSummary: false,
    includeCategory: false,
  };
  it('[나]·[보낸 사람]·[받는 사람]·[제목]·[본문] 순서로 조립', () => {
    expect(buildPersonalUserMessage(base)).toBe(
      '[나] 주소: gd@acme.com, gd@gmail.com\n' +
        '[보낸 사람] 김민수 <minsu@acme.com>\n' +
        '[받는 사람] 나는 To · To 1명 · CC 3명\n' +
        '[제목] 배포 일정 확인 부탁드립니다\n' +
        '[본문]\n금요일까지 확인 부탁드립니다',
    );
  });
  it('CC·없음·알 수 없음 표기', () => {
    expect(buildPersonalUserMessage({ ...base, recipient: { myRole: 'CC', toCount: 2, ccCount: 1 } })).toContain('[받는 사람] 나는 CC · To 2명 · CC 1명');
    expect(buildPersonalUserMessage({ ...base, recipient: { myRole: 'NONE', toCount: 2, ccCount: 0 } })).toContain('[받는 사람] 나는 To·CC 에 없음');
    expect(buildPersonalUserMessage({ ...base, recipient: { myRole: 'UNKNOWN', toCount: 0, ccCount: 0 } })).not.toContain('[받는 사람]');
  });
  it('이름이 없으면 주소만, 내 주소가 없으면 [나] 생략', () => {
    const msg = buildPersonalUserMessage({ ...base, fromName: '', me: { addresses: [] } });
    expect(msg).toContain('[보낸 사람] minsu@acme.com');
    expect(msg).not.toContain('[나]');
  });
});

describe('runMailAnalyzeContent / runMailAnalyzePersonal', () => {
  it('플래그대로 조립한 프롬프트로 호출하고 파싱 결과를 돌려준다', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '{"category":"업무","summary":"• 요약"}' }),
    ]);
    const out = await runMailAnalyzeContent(
      { ...cfg, subject: 's', from: 'a@b', body: '본문', autoGenerated: false, includeCategory: true, includeSummary: true },
      { client: fakeClient },
    );
    expect(out).toEqual({ category: '업무', summary: '• 요약' });
    const arg = vi.mocked(runSdkCollect).mock.calls[0][0];
    expect(arg.systemPrompt).toContain('"summary"');
    expect(arg.userMessage).toContain('[본문]\n본문');
  });

  it('개인 분석 — needsReply 만 요청', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '{"needsReply":true}' }),
    ]);
    const out = await runMailAnalyzePersonal(
      {
        ...cfg,
        subject: 's',
        fromAddress: 'a@b.com',
        fromName: '',
        body: '확인 부탁',
        autoGenerated: false,
        me: { addresses: ['me@x.com'] },
        recipient: { myRole: 'TO', toCount: 1, ccCount: 0 },
        includeNeedsReply: true,
        includePersonalSummary: false,
        includeCategory: false,
      },
      { client: fakeClient },
    );
    expect(out).toEqual({ needsReply: true, personalSummary: null, personalSummaryValid: false, category: null });
    expect(vi.mocked(runSdkCollect).mock.calls[0][0].systemPrompt).not.toContain('personalSummary');
  });
});
