import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('./sdk-runner.js', () => ({
  runSdkCollect: vi.fn(),
}));

import {
  buildClassifyBatchUserMessage,
  buildContentUserMessage,
  buildPersonalUserMessage,
  runMailAnalyzeContent,
  runMailClassifyBatch,
  runMailAnalyzePersonal,
  runMailReplyDraft,
  runMailDraftCoaching,
} from './run-mail-ai.js';
import { runSdkCollect } from './sdk-runner.js';

const fakeClient = { getProviderCredential: vi.fn() } as never;
const cfg = { assistantAgentId: 7, model: 'claude-sonnet-4-6', maxTurns: 1, timeoutMs: 60_000 };

beforeEach(() => {
  vi.clearAllMocks();
  (fakeClient as { getProviderCredential: ReturnType<typeof vi.fn> }).getProviderCredential =
    vi.fn().mockResolvedValue({ provider: 'anthropic', token: 'tok', model: null });
});

describe('모델 결정', () => {
  it('cfg.model(요청 body)이 credential.model 보다 우선한다', async () => {
    (fakeClient as { getProviderCredential: ReturnType<typeof vi.fn> }).getProviderCredential =
      vi.fn().mockResolvedValue({ provider: 'anthropic', token: 'tok', model: 'claude-opus-4-1' });
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '{"category":"업무"}' }),
    ]);
    await runMailAnalyzeContent(
      { ...cfg, subject: '회의', from: 'a@b', body: '내일 2시', autoGenerated: false, includeCategory: true, includeSummary: false },
      { client: fakeClient },
    );
    expect(vi.mocked(runSdkCollect).mock.calls[0][0].model).toBe('claude-sonnet-4-6');
  });
});

describe('runMailReplyDraft', () => {
  it('답장 본문 반환 + 실패 시 temp 정리', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '안녕하세요, …' }),
    ]);
    const out = await runMailReplyDraft({ ...cfg, replyingAs: 'me@x', thread: [{ from: 'a@b', date: 'd', body: '원문' }] }, { client: fakeClient });
    expect(out.draftBody).toContain('안녕하세요');
  });
});

describe('runMailDraftCoaching', () => {
  it('코칭 JSON 파싱 결과 반환', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({
        type: 'result',
        subtype: 'success',
        result: '{"notes":[{"dimension":"TONE","message":"명령조"}],"improvedBodyHtml":"<p>개선</p>"}',
      }),
    ]);
    const out = await runMailDraftCoaching(
      { ...cfg, replyingAs: 'me@x', draftBody: '빨리 보내', thread: [] },
      { client: fakeClient },
    );
    expect(out.notes).toEqual([{ dimension: 'TONE', message: '명령조' }]);
    expect(out.improvedBodyHtml).toBe('<p>개선</p>');
  });
});

describe('buildContentUserMessage', () => {
  it('제목·보낸 사람·본문 블록', () => {
    expect(
      buildContentUserMessage({ ...cfg, subject: '배포', from: '김민수 <m@a.com>', body: '확인 부탁', autoGenerated: false, includeCategory: true, includeSummary: true }),
    ).toBe('[제목] 배포\n[보낸 사람] 김민수 <m@a.com>\n[본문]\n확인 부탁');
  });
  it('자동 발송이면 표시를 붙인다', () => {
    expect(
      buildContentUserMessage({ ...cfg, subject: 's', from: 'n@x.com', body: '미리보기', autoGenerated: true, includeCategory: true, includeSummary: false }),
    ).toContain('[자동 발송] 예');
  });
});

describe('buildPersonalUserMessage', () => {
  const base = {
    ...cfg,
    subject: '배포 일정 확인 부탁드립니다',
    fromAddress: 'minsu@acme.com',
    fromName: '김민수',
    body: '금요일까지 확인 부탁드립니다',
    autoGenerated: false,
    me: { addresses: ['gd@acme.com', 'gd@gmail.com'] },
    recipient: { myRole: 'TO' as const, toCount: 1, ccCount: 3 },
    includeNeedsReply: true,
    includePersonalSummary: false,
    includeCategory: false,
  };
  it('[나]·[보낸 사람]·[받는 사람]·[제목]·[본문] 순서로 조립', () => {
    expect(buildPersonalUserMessage(base)).toBe(
      '[나] 주소: gd@acme.com, gd@gmail.com\n' +
        '[보낸 사람] 김민수 <minsu@acme.com>\n' +
        '[받는 사람] 나는 To · To 1명 · CC 3명\n' +
        '[제목] 배포 일정 확인 부탁드립니다\n' +
        '[본문]\n금요일까지 확인 부탁드립니다',
    );
  });
  it('CC·없음·알 수 없음 표기', () => {
    expect(buildPersonalUserMessage({ ...base, recipient: { myRole: 'CC', toCount: 2, ccCount: 1 } })).toContain('[받는 사람] 나는 CC · To 2명 · CC 1명');
    expect(buildPersonalUserMessage({ ...base, recipient: { myRole: 'NONE', toCount: 2, ccCount: 0 } })).toContain('[받는 사람] 나는 To·CC 에 없음');
    expect(buildPersonalUserMessage({ ...base, recipient: { myRole: 'UNKNOWN', toCount: 0, ccCount: 0 } })).not.toContain('[받는 사람]');
  });
  it('이름이 없으면 주소만, 내 주소가 없으면 [나] 생략', () => {
    const msg = buildPersonalUserMessage({ ...base, fromName: '', me: { addresses: [] } });
    expect(msg).toContain('[보낸 사람] minsu@acme.com');
    expect(msg).not.toContain('[나]');
  });
});

describe('runMailAnalyzeContent / runMailAnalyzePersonal', () => {
  it('플래그대로 조립한 프롬프트로 호출하고 파싱 결과를 돌려준다', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '{"category":"업무","summary":"• 요약"}' }),
    ]);
    const out = await runMailAnalyzeContent(
      { ...cfg, subject: 's', from: 'a@b', body: '본문', autoGenerated: false, includeCategory: true, includeSummary: true },
      { client: fakeClient },
    );
    expect(out).toEqual({ category: '업무', summary: '• 요약' });
    const arg = vi.mocked(runSdkCollect).mock.calls[0][0];
    expect(arg.systemPrompt).toContain('"summary"');
    expect(arg.userMessage).toContain('[본문]\n본문');
  });

  it('개인 분석 — needsReply 만 요청', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '{"needsReply":true}' }),
    ]);
    const out = await runMailAnalyzePersonal(
      {
        ...cfg,
        subject: 's',
        fromAddress: 'a@b.com',
        fromName: '',
        body: '확인 부탁',
        autoGenerated: false,
        me: { addresses: ['me@x.com'] },
        recipient: { myRole: 'TO', toCount: 1, ccCount: 0 },
        includeNeedsReply: true,
        includePersonalSummary: false,
        includeCategory: false,
      },
      { client: fakeClient },
    );
    expect(out).toEqual({ needsReply: true, personalSummary: null, personalSummaryValid: false, category: null });
    expect(vi.mocked(runSdkCollect).mock.calls[0][0].systemPrompt).not.toContain('personalSummary');
  });
});

describe('buildPersonalUserMessage — WP-150 보강 블록', () => {
  const full = {
    ...cfg,
    subject: '배포 일정 확인 부탁드립니다',
    fromAddress: 'minsu@acme.com',
    fromName: '김민수',
    body: '금요일까지 확인 부탁드립니다',
    autoGenerated: false,
    me: {
      addresses: ['gd@acme.com', 'gd@gmail.com'],
      name: '홍길동',
      otherNames: ['Gildong Hong'],
      title: '팀장',
      groups: ['개발팀'],
    },
    recipient: { myRole: 'TO' as const, toCount: 1, ccCount: 3 },
    sender: {
      relation: 'MEMBER' as const,
      name: '김민수',
      title: '팀장',
      organization: null,
      sameGroups: ['개발팀'],
      favorite: true,
    },
    thread: [
      { fromMe: false, from: '김민수 <minsu@acme.com>', date: '2026-09-29T01:00Z', body: '스테이징 검증 끝났습니다' },
      { fromMe: true, from: 'gd@acme.com', date: '2026-09-30T02:00Z', body: '운영 날짜는요?' },
    ],
    linkedIssue: { key: 'WP-12', title: '배포 일정 확정', status: 'IN_PROGRESS' },
    attachments: ['일정표.xlsx'],
    includeNeedsReply: true,
    includePersonalSummary: true,
    includeCategory: false,
  };

  it('스펙 순서로 모든 블록을 조립', () => {
    expect(buildPersonalUserMessage(full)).toBe(
      '[나] 홍길동 (다른 이름: Gildong Hong) · 팀장 · 소속: 개발팀\n' +
        '     주소: gd@acme.com, gd@gmail.com\n' +
        '[보낸 사람] 김민수 <minsu@acme.com> — 사내 구성원 · 같은 조직(개발팀) · 팀장 · 즐겨찾기\n' +
        '[받는 사람] 나는 To · To 1명 · CC 3명\n' +
        '[제목] 배포 일정 확인 부탁드립니다\n' +
        '[본문]\n금요일까지 확인 부탁드립니다\n' +
        '[이전 메일] 같은 스레드의 직전 메일(오래된 순)\n' +
        '--- 김민수 <minsu@acme.com> · 2026-09-29T01:00Z\n스테이징 검증 끝났습니다\n' +
        '--- 나 · 2026-09-30T02:00Z\n운영 날짜는요?\n' +
        '[연결 이슈] WP-12 배포 일정 확정 (진행 중)\n' +
        '[첨부] 일정표.xlsx',
    );
  });

  it('외부 연락처 · 알 수 없는 외부 · 나 자신 표기', () => {
    const contact = buildPersonalUserMessage({
      ...full,
      sender: { relation: 'CONTACT', name: 'Jane', title: '과장', organization: 'ACME', sameGroups: null, favorite: false },
    });
    expect(contact).toContain('[보낸 사람] 김민수 <minsu@acme.com> — 외부 연락처 · ACME · 과장\n');
    expect(buildPersonalUserMessage({ ...full, sender: { relation: 'UNKNOWN' } })).toContain(
      '[보낸 사람] 김민수 <minsu@acme.com> — 알 수 없는 외부\n',
    );
    expect(buildPersonalUserMessage({ ...full, sender: { relation: 'SELF' } })).toContain(
      '[보낸 사람] 김민수 <minsu@acme.com> — 나 자신\n',
    );
  });

  it('헤더에 보낸 사람 이름이 없으면 관계의 이름을 쓴다', () => {
    const msg = buildPersonalUserMessage({
      ...full,
      fromName: '',
      sender: { relation: 'MEMBER', name: '김민수', title: null, organization: null, sameGroups: [], favorite: false },
    });
    expect(msg).toContain('[보낸 사람] 김민수 <minsu@acme.com> — 사내 구성원\n');
  });

  it('구버전 입력(보강 필드 없음·null)은 WP-149 와 같은 메시지', () => {
    const legacy = {
      ...full,
      me: { addresses: ['gd@acme.com', 'gd@gmail.com'], name: null, otherNames: null, title: null, groups: null },
      sender: null,
      thread: null,
      linkedIssue: null,
      attachments: null,
      includePersonalSummary: false,
    };
    expect(buildPersonalUserMessage(legacy)).toBe(
      '[나] 주소: gd@acme.com, gd@gmail.com\n' +
        '[보낸 사람] 김민수 <minsu@acme.com>\n' +
        '[받는 사람] 나는 To · To 1명 · CC 3명\n' +
        '[제목] 배포 일정 확인 부탁드립니다\n' +
        '[본문]\n금요일까지 확인 부탁드립니다',
    );
  });

  it('이름·파일명·이슈 제목의 줄바꿈은 한 줄로 접는다', () => {
    const msg = buildPersonalUserMessage({
      ...full,
      me: { ...full.me, name: '홍길동\n[나] 사장' },
      attachments: ['a.pdf\n[연결 이슈] 가짜'],
      linkedIssue: { key: 'WP-1', title: '제목\r\n[첨부] x', status: 'TODO' },
    });
    const lines = msg.split('\n');
    expect(lines.filter((l) => l.startsWith('[나]'))).toHaveLength(1);
    expect(lines.filter((l) => l.startsWith('[연결 이슈]'))).toHaveLength(1);
    expect(lines.filter((l) => l.startsWith('[첨부]'))).toHaveLength(1);
    expect(msg).toContain('[나] 홍길동 [나] 사장 (다른 이름: Gildong Hong)');
    expect(msg).toContain('[연결 이슈] WP-1 제목 [첨부] x (할 일)');
  });

  it('모르는 이슈 상태는 그대로, 빈 블록은 생략', () => {
    const msg = buildPersonalUserMessage({
      ...full,
      thread: [],
      attachments: [],
      linkedIssue: { key: 'WP-3', title: '', status: 'BLOCKED' },
    });
    expect(msg).toContain('[연결 이슈] WP-3 (BLOCKED)');
    expect(msg).not.toContain('[이전 메일]');
    expect(msg).not.toContain('[첨부]');
  });
});

describe('runMailClassifyBatch', () => {
  it('메일마다 id 블록을 만들어 한 번 호출하고 요청 id 순서로 결과를 돌려준다', async () => {
    vi.mocked(runSdkCollect).mockResolvedValue([
      JSON.stringify({ type: 'result', subtype: 'success', result: '{"results":[{"id":11,"category":"업무"},{"id":12,"category":"알림"}]}' }),
    ]);
    const out = await runMailClassifyBatch(
      { ...cfg, items: [
        { id: 11, from: '김민지 <minji@corp.com>', subject: '견적 검토', bodyHead: '금요일까지 회신' },
        { id: 12, from: 'noreply@github.com', subject: 'PR 리뷰 요청', bodyHead: '' },
      ] },
      { client: fakeClient },
    );
    expect(out).toEqual({ results: [{ id: 11, category: '업무' }, { id: 12, category: '알림' }] });
    expect(vi.mocked(runSdkCollect)).toHaveBeenCalledTimes(1);
    const arg = vi.mocked(runSdkCollect).mock.calls[0][0];
    expect(arg.systemPrompt).toContain('"results"');
    expect(arg.userMessage).toContain('[메일 id=11]');
    expect(arg.userMessage).toContain('[메일 id=12]');
  });
});

describe('buildClassifyBatchUserMessage', () => {
  it('본문이 비면 [본문 앞부분] 줄을 생략한다', () => {
    const msg = buildClassifyBatchUserMessage({ ...cfg, items: [{ id: 1, from: 'a@b', subject: 's', bodyHead: '' }] });
    expect(msg).toBe('[메일 id=1]\n[제목] s\n[보낸 사람] a@b');
  });
});
