// 7d: 메일 AI 러너 — 비서 OAuth 토큰 fetch → SDK 단발 실행 → 파서.
// 원본/개인 분석·답장·코칭·이슈 초안 모두 도구 미사용 텍스트 in/out. MCP 서버·임시 config 불필요.
import { runnerFor } from './agent-runner.js';
import { finalText } from './runner-events.js';
import {
  parseContentAnalysisJson,
  parseDraftCoachingJson,
  parseIssueDraftJson,
  parsePersonalAnalysisJson,
} from './mail-parser.js';
import {
  buildContentAnalysisPrompt,
  buildPersonalAnalysisPrompt,
  MAIL_DRAFT_COACHING_PROMPT,
  MAIL_ISSUE_DRAFT_PROMPT,
  MAIL_REPLY_DRAFT_PROMPT,
} from './mail-system-prompt.js';
import { DEFAULT_MODEL } from './model-defaults.js';
import type { RunAgentDeps } from './run-agent.js';

interface BaseConfig {
  assistantAgentId: number;
  model: string;
  maxTurns: number;
  timeoutMs: number;
}
export interface ThreadMsg { from: string; date: string; body: string; }
export interface ReplyDraftInput extends BaseConfig { thread: ThreadMsg[]; replyingAs: string; }
export interface DraftCoachingInput extends BaseConfig {
  draftBody: string;
  thread: ThreadMsg[];
  replyingAs: string;
}

// 공통: 토큰 fetch → SDK 단발 실행 → 최종 텍스트. 도구 미사용이라 MCP 서버/임시 config 불필요.
// export: issue 등 다른 AI 러너도 동일 패턴으로 재사용.
export async function runText(
  systemPrompt: string,
  userMessage: string,
  cfg: BaseConfig,
  deps: RunAgentDeps,
  tag: string,
): Promise<string> {
  const credential = await deps.client.getProviderCredential(cfg.assistantAgentId);
  const events = await runnerFor(credential).collect({
    userMessage,
    systemPrompt,
    // 우선순위: 요청 body(cfg.model) > redeem 응답(credential.model) > env/기본값.
    model: cfg.model ?? credential.model ?? process.env.WORKPLACE_AI_MODEL ?? DEFAULT_MODEL,
    maxTurns: cfg.maxTurns,
    credential,
    agentId: cfg.assistantAgentId,
    timeoutMs: cfg.timeoutMs,
    logTag: `${tag}:${cfg.assistantAgentId}`,
    includePartialMessages: false,
  });
  return finalText(events);
}

// 답장 초안: 스레드 전체 + 발신자 → {draftBody}
export async function runMailReplyDraft(
  input: ReplyDraftInput,
  deps: RunAgentDeps,
): Promise<{ draftBody: string }> {
  const convo = input.thread.map((m) => `--- ${m.from} (${m.date})\n${m.body}`).join('\n\n');
  const userMessage = `당신은 ${input.replyingAs} 로서 아래 대화의 마지막 메일에 답장합니다.\n\n${convo}`;
  return { draftBody: (await runText(MAIL_REPLY_DRAFT_PROMPT, userMessage, input, deps, 'mail-reply-draft')).trim() };
}

export interface IssueDraftInput extends BaseConfig {
  subject: string;
  body: string;
  candidateProjects: { key: string; name: string }[];
}

// #520 메일→이슈 초안: 제목·본문·우선순위 + 후보 중 추천 projectKey.
export async function runMailIssueDraft(
  input: IssueDraftInput,
  deps: RunAgentDeps,
): Promise<{ title: string; body: string; priority: string; projectKey?: string }> {
  const projects = input.candidateProjects.map((p) => `- ${p.key}: ${p.name}`).join('\n') || '- (없음)';
  const userMessage = `제목: ${input.subject}\n\n본문:\n${input.body}\n\n후보 프로젝트:\n${projects}`;
  return parseIssueDraftJson(
    await runText(MAIL_ISSUE_DRAFT_PROMPT, userMessage, input, deps, 'mail-issue-draft'),
  );
}

// 초안 코칭: 내 초안(+답장이면 원문 스레드) → {notes, improvedBodyHtml}
export async function runMailDraftCoaching(
  input: DraftCoachingInput,
  deps: RunAgentDeps,
): Promise<{ notes: { dimension: string; message: string }[]; improvedBodyHtml: string }> {
  const convo = input.thread.map((m) => `--- ${m.from} (${m.date})\n${m.body}`).join('\n\n');
  const context = convo ? `원문 대화(답장 상황):\n${convo}\n\n` : '';
  const userMessage = `${context}당신은 ${input.replyingAs} 입니다. 아래 내 초안을 코칭하세요.\n\n내 초안:\n${input.draftBody}`;
  const text = await runText(MAIL_DRAFT_COACHING_PROMPT, userMessage, input, deps, 'mail-draft-coaching');
  return parseDraftCoachingJson(text);
}

// ───────────────────────────── WP-149 원본/개인 분석 ─────────────────────────────

/** ③ 원본 분석 입력 — 새 본문(api 의 NewContentExtractor 결과, 자동 발송이면 미리보기). */
export interface AnalyzeContentInput extends BaseConfig {
  subject: string;
  from: string;
  body: string;
  autoGenerated: boolean;
  includeCategory: boolean;
  includeSummary: boolean;
}

/** To/CC 에서 [나]의 위치. UNKNOWN = 받는 사람 정보 없음(블록 생략). */
export type RecipientRole = 'TO' | 'CC' | 'NONE' | 'UNKNOWN';

/** 보낸 사람과 [나]의 관계(WP-150). SELF=나 자신, MEMBER=사내 구성원, CONTACT=내가 볼 수 있는 외부 연락처, UNKNOWN=알 수 없는 외부. */
export type SenderRelationKind = 'SELF' | 'MEMBER' | 'CONTACT' | 'UNKNOWN';

/** [나] — 주소는 필수(WP-149, ⑤ 규칙과 같은 집합). 이름·다른 이름·직함·소속은 WP-150 보강이며 api 가 조회에 실패하면 null 이다. */
export interface MeInfo {
  addresses: string[];
  name?: string | null;
  otherNames?: string[] | null;
  title?: string | null;
  groups?: string[] | null;
}

/** [보낸 사람] 관계 꼬리 — 관계 조회에 실패하면 api 가 null 로 보내고 꼬리를 생략한다. */
export interface SenderInfo {
  relation: SenderRelationKind;
  name?: string | null;
  title?: string | null;
  organization?: string | null;
  sameGroups?: string[] | null;
  favorite?: boolean | null;
}

/** [이전 메일] 1건 — 같은 스레드 직전 메일의 새로 쓴 부분(앞 500자, api 가 자름). */
export interface PriorMailInfo {
  fromMe: boolean;
  from: string;
  date: string;
  body: string;
}

/** [연결 이슈] — 이 메일로 만든 이슈. status 는 TODO|IN_PROGRESS|DONE|CANCELED. */
export interface LinkedIssueInfo {
  key: string;
  title: string;
  status: string;
}

/**
 * ④ 개인 분석 입력. WP-149 의 [나] 주소·받는 사람 위치에 WP-150 이 프로필·관계·이전 메일·연결 이슈·첨부를 더했다. 보강 필드는 모두 선택이다 —
 * 구버전 api 는 보내지 않고, 조회에 실패한 블록은 null 로 온다.
 */
export interface AnalyzePersonalInput extends BaseConfig {
  subject: string;
  fromAddress: string;
  fromName: string;
  body: string;
  autoGenerated: boolean;
  me: MeInfo;
  recipient: { myRole: RecipientRole; toCount: number; ccCount: number };
  sender?: SenderInfo | null;
  thread?: PriorMailInfo[] | null;
  linkedIssue?: LinkedIssueInfo | null;
  attachments?: string[] | null;
  includeNeedsReply: boolean;
  includePersonalSummary: boolean;
  includeCategory: boolean;
}

/** ③ user message — [제목]·[보낸 사람]·([자동 발송])·[본문]. */
export function buildContentUserMessage(input: AnalyzeContentInput): string {
  const lines = [`[제목] ${input.subject}`, `[보낸 사람] ${input.from}`];
  if (input.autoGenerated) lines.push('[자동 발송] 예');
  lines.push('[본문]', input.body);
  return lines.join('\n');
}

/** [받는 사람] 줄 — 위치를 모르면 null(블록 생략). */
function recipientLine(r: AnalyzePersonalInput['recipient']): string | null {
  const counts = `To ${r.toCount}명 · CC ${r.ccCount}명`;
  switch (r.myRole) {
    case 'TO':
      return `[받는 사람] 나는 To · ${counts}`;
    case 'CC':
      return `[받는 사람] 나는 CC · ${counts}`;
    case 'NONE':
      return `[받는 사람] 나는 To·CC 에 없음 · ${counts}`;
    default:
      return null;
  }
}

/**
 * 한 줄 값 — 줄바꿈을 공백으로 접는다. 표시 이름·파일명·이슈 제목은 발신자나 다른 사용자가 정할 수 있어, 줄바꿈을 넣어 "[나] …" 같은 가짜 블록
 * 줄을 만들지 못하게 한다(WP-150). 본문은 여러 줄 그대로 둔다.
 */
function oneLine(s: string | null | undefined): string {
  return (s ?? '').replace(/\s*[\r\n]+\s*/g, ' ').trim();
}

/** 한 줄 값 목록 — 접은 뒤 빈 값은 뺀다. */
function oneLines(list: string[] | null | undefined): string[] {
  return (list ?? []).map(oneLine).filter((s) => s.length > 0);
}

const RELATION_LABEL: Record<SenderRelationKind, string> = {
  SELF: '나 자신',
  MEMBER: '사내 구성원',
  CONTACT: '외부 연락처',
  UNKNOWN: '알 수 없는 외부',
};

const ISSUE_STATUS_LABEL: Record<string, string> = {
  TODO: '할 일',
  IN_PROGRESS: '진행 중',
  DONE: '완료',
  CANCELED: '취소',
};

/**
 * [나] 줄 — 이름이 있으면 "이름 (다른 이름: …) · 직함 · 소속: …" + 들여쓴 주소 줄, 없으면 WP-149 처럼 "[나] 주소: …" 한 줄.
 * ⚠️ api `UserMailProfile.render()` 와 같은 형식(양쪽 테스트로 고정).
 */
function meLines(me: MeInfo): string[] {
  const addresses = oneLines(me.addresses);
  const addressText = addresses.length > 0 ? `주소: ${addresses.join(', ')}` : null;
  const name = oneLine(me.name);
  if (!name) return addressText ? [`[나] ${addressText}`] : [];
  const others = oneLines(me.otherNames);
  const head = [others.length > 0 ? `${name} (다른 이름: ${others.join(', ')})` : name];
  const title = oneLine(me.title);
  if (title) head.push(title);
  const groups = oneLines(me.groups);
  if (groups.length > 0) head.push(`소속: ${groups.join(', ')}`);
  const lines = [`[나] ${head.join(' · ')}`];
  if (addressText) lines.push(`     ${addressText}`);
  return lines;
}

/** [보낸 사람] 관계 꼬리 — 사내 구성원은 같은 조직·직함·즐겨찾기, 외부 연락처는 소속 회사·직함·즐겨찾기. */
function senderTags(s: SenderInfo | null | undefined): string[] {
  if (!s) return [];
  const tags = [RELATION_LABEL[s.relation]];
  if (s.relation === 'MEMBER') {
    const groups = oneLines(s.sameGroups);
    if (groups.length > 0) tags.push(`같은 조직(${groups.join(', ')})`);
  }
  if (s.relation === 'CONTACT') {
    const org = oneLine(s.organization);
    if (org) tags.push(org);
  }
  if (s.relation === 'MEMBER' || s.relation === 'CONTACT') {
    const title = oneLine(s.title);
    if (title) tags.push(title);
    if (s.favorite) tags.push('즐겨찾기');
  }
  return tags;
}

/** [보낸 사람] 줄 — 헤더 이름이 없으면 관계(사내 구성원·외부 연락처)의 이름을 쓴다. */
function senderLine(input: AnalyzePersonalInput): string {
  const address = oneLine(input.fromAddress);
  const known = input.sender?.relation === 'MEMBER' || input.sender?.relation === 'CONTACT';
  const name = oneLine(input.fromName) || (known ? oneLine(input.sender?.name) : '');
  const base = name ? `${name} <${address}>` : address;
  const tags = senderTags(input.sender);
  return tags.length > 0 ? `[보낸 사람] ${base} — ${tags.join(' · ')}` : `[보낸 사람] ${base}`;
}

/** [이전 메일] 블록 — 오래된 순, 각 메일은 "--- 보낸 사람 · 날짜" 머리줄 + 새로 쓴 부분. 없으면 빈 배열. */
function threadLines(thread: PriorMailInfo[] | null | undefined): string[] {
  if (!thread || thread.length === 0) return [];
  const lines = ['[이전 메일] 같은 스레드의 직전 메일(오래된 순)'];
  for (const m of thread) {
    const who = m.fromMe ? '나' : oneLine(m.from) || '(알 수 없음)';
    const date = oneLine(m.date);
    lines.push(date ? `--- ${who} · ${date}` : `--- ${who}`, m.body);
  }
  return lines;
}

/** [연결 이슈] 줄 — "키 제목 (상태)". 키가 없으면 생략, 모르는 상태 코드는 그대로. */
function linkedIssueLine(issue: LinkedIssueInfo | null | undefined): string | null {
  if (!issue) return null;
  const key = oneLine(issue.key);
  if (!key) return null;
  const title = oneLine(issue.title);
  const status = ISSUE_STATUS_LABEL[issue.status] ?? oneLine(issue.status);
  return `[연결 이슈] ${key}${title ? ` ${title}` : ''}${status ? ` (${status})` : ''}`;
}

/** [첨부] 줄 — 파일 이름을 쉼표로. 없으면 생략. */
function attachmentsLine(names: string[] | null | undefined): string | null {
  const list = oneLines(names);
  return list.length > 0 ? `[첨부] ${list.join(', ')}` : null;
}

/**
 * ④ user message — [나]·[보낸 사람]·[받는 사람]·[제목]·([자동 발송])·[본문]·[이전 메일]·[연결 이슈]·[첨부]. 비어 있거나 오지 않은 블록은 뺀다 —
 * 보강 필드가 없는 구버전 입력은 WP-149 와 같은 메시지가 된다.
 */
export function buildPersonalUserMessage(input: AnalyzePersonalInput): string {
  const lines: string[] = [...meLines(input.me), senderLine(input)];
  const recipient = recipientLine(input.recipient);
  if (recipient) lines.push(recipient);
  lines.push(`[제목] ${oneLine(input.subject)}`);
  if (input.autoGenerated) lines.push('[자동 발송] 예');
  lines.push('[본문]', input.body);
  lines.push(...threadLines(input.thread));
  const issue = linkedIssueLine(input.linkedIssue);
  if (issue) lines.push(issue);
  const files = attachmentsLine(input.attachments);
  if (files) lines.push(files);
  return lines.join('\n');
}

// ③ 원본 분석: {category?, summary?}
export async function runMailAnalyzeContent(
  input: AnalyzeContentInput,
  deps: RunAgentDeps,
): Promise<{ category: string | null; summary: string | null }> {
  const flags = { includeCategory: input.includeCategory, includeSummary: input.includeSummary };
  const text = await runText(buildContentAnalysisPrompt(flags), buildContentUserMessage(input), input, deps, 'mail-analyze-content');
  return parseContentAnalysisJson(text, flags);
}

// ④ 개인 분석: {needsReply?, personalSummary?, personalSummaryValid, category?}
export async function runMailAnalyzePersonal(
  input: AnalyzePersonalInput,
  deps: RunAgentDeps,
): Promise<{ needsReply: boolean | null; personalSummary: string | null; personalSummaryValid: boolean; category: string | null }> {
  const flags = {
    includeNeedsReply: input.includeNeedsReply,
    includePersonalSummary: input.includePersonalSummary,
    includeCategory: input.includeCategory,
  };
  const text = await runText(buildPersonalAnalysisPrompt(flags), buildPersonalUserMessage(input), input, deps, 'mail-analyze-personal');
  return parsePersonalAnalysisJson(text, flags);
}
