// 7d: 메일 AI 러너 — 비서 OAuth 토큰 fetch → SDK 단발 실행 → 파서.
// 분류/요약/답장 모두 도구 미사용 텍스트 in/out. MCP 서버·임시 config 불필요.
import { runnerFor } from './agent-runner.js';
import { finalText } from './runner-events.js';
import {
  parseClassifyJson,
  parseContentAnalysisJson,
  parseDraftCoachingJson,
  parseIssueDraftJson,
  parsePersonalAnalysisJson,
} from './mail-parser.js';
import {
  buildContentAnalysisPrompt,
  buildPersonalAnalysisPrompt,
  MAIL_CLASSIFY_PROMPT,
  MAIL_DRAFT_COACHING_PROMPT,
  MAIL_ISSUE_DRAFT_PROMPT,
  MAIL_REPLY_DRAFT_PROMPT,
  MAIL_SUMMARIZE_PROMPT,
} from './mail-system-prompt.js';
import { DEFAULT_MODEL } from './model-defaults.js';
import type { RunAgentDeps } from './run-agent.js';

interface BaseConfig {
  assistantAgentId: number;
  model: string;
  maxTurns: number;
  timeoutMs: number;
}
export interface ClassifyInput extends BaseConfig { subject: string; from: string; snippet: string; }
export interface SummarizeInput extends BaseConfig { subject: string; from: string; body: string; }
export interface ThreadMsg { from: string; date: string; body: string; }
export interface ReplyDraftInput extends BaseConfig { thread: ThreadMsg[]; replyingAs: string; }
export interface DraftCoachingInput extends BaseConfig {
  draftBody: string;
  thread: ThreadMsg[];
  replyingAs: string;
}

// 공통: 토큰 fetch → SDK 단발 실행 → 최종 텍스트. 도구 미사용이라 MCP 서버/임시 config 불필요.
// export: issue 등 다른 AI 러너도 동일 패턴으로 재사용.
export async function runText(
  systemPrompt: string,
  userMessage: string,
  cfg: BaseConfig,
  deps: RunAgentDeps,
  tag: string,
): Promise<string> {
  const credential = await deps.client.getProviderCredential(cfg.assistantAgentId);
  const events = await runnerFor(credential).collect({
    userMessage,
    systemPrompt,
    // 우선순위: 요청 body(cfg.model) > redeem 응답(credential.model) > env/기본값.
    model: cfg.model ?? credential.model ?? process.env.WORKPLACE_AI_MODEL ?? DEFAULT_MODEL,
    maxTurns: cfg.maxTurns,
    credential,
    agentId: cfg.assistantAgentId,
    timeoutMs: cfg.timeoutMs,
    logTag: `${tag}:${cfg.assistantAgentId}`,
    includePartialMessages: false,
  });
  return finalText(events);
}

// 메일 분류: 제목·보낸사람·미리보기 → {category, needsReply}
export async function runMailClassify(
  input: ClassifyInput,
  deps: RunAgentDeps,
): Promise<{ category: string; needsReply: boolean }> {
  const userMessage = `제목: ${input.subject}\n보낸사람: ${input.from}\n미리보기: ${input.snippet}`;
  return parseClassifyJson(await runText(MAIL_CLASSIFY_PROMPT, userMessage, input, deps, 'mail-classify'));
}

// 메일 요약: 제목·보낸사람·본문 → {summary}
export async function runMailSummarize(
  input: SummarizeInput,
  deps: RunAgentDeps,
): Promise<{ summary: string }> {
  const userMessage = `제목: ${input.subject}\n보낸사람: ${input.from}\n\n본문:\n${input.body}`;
  return { summary: (await runText(MAIL_SUMMARIZE_PROMPT, userMessage, input, deps, 'mail-summarize')).trim() };
}

// 답장 초안: 스레드 전체 + 발신자 → {draftBody}
export async function runMailReplyDraft(
  input: ReplyDraftInput,
  deps: RunAgentDeps,
): Promise<{ draftBody: string }> {
  const convo = input.thread.map((m) => `--- ${m.from} (${m.date})\n${m.body}`).join('\n\n');
  const userMessage = `당신은 ${input.replyingAs} 로서 아래 대화의 마지막 메일에 답장합니다.\n\n${convo}`;
  return { draftBody: (await runText(MAIL_REPLY_DRAFT_PROMPT, userMessage, input, deps, 'mail-reply-draft')).trim() };
}

export interface IssueDraftInput extends BaseConfig {
  subject: string;
  body: string;
  candidateProjects: { key: string; name: string }[];
}

// #520 메일→이슈 초안: 제목·본문·우선순위 + 후보 중 추천 projectKey.
export async function runMailIssueDraft(
  input: IssueDraftInput,
  deps: RunAgentDeps,
): Promise<{ title: string; body: string; priority: string; projectKey?: string }> {
  const projects = input.candidateProjects.map((p) => `- ${p.key}: ${p.name}`).join('\n') || '- (없음)';
  const userMessage = `제목: ${input.subject}\n\n본문:\n${input.body}\n\n후보 프로젝트:\n${projects}`;
  return parseIssueDraftJson(
    await runText(MAIL_ISSUE_DRAFT_PROMPT, userMessage, input, deps, 'mail-issue-draft'),
  );
}

// 초안 코칭: 내 초안(+답장이면 원문 스레드) → {notes, improvedBodyHtml}
export async function runMailDraftCoaching(
  input: DraftCoachingInput,
  deps: RunAgentDeps,
): Promise<{ notes: { dimension: string; message: string }[]; improvedBodyHtml: string }> {
  const convo = input.thread.map((m) => `--- ${m.from} (${m.date})\n${m.body}`).join('\n\n');
  const context = convo ? `원문 대화(답장 상황):\n${convo}\n\n` : '';
  const userMessage = `${context}당신은 ${input.replyingAs} 입니다. 아래 내 초안을 코칭하세요.\n\n내 초안:\n${input.draftBody}`;
  const text = await runText(MAIL_DRAFT_COACHING_PROMPT, userMessage, input, deps, 'mail-draft-coaching');
  return parseDraftCoachingJson(text);
}

// ───────────────────────────── WP-149 원본/개인 분석 ─────────────────────────────

/** ③ 원본 분석 입력 — 새 본문(api 의 NewContentExtractor 결과, 자동 발송이면 미리보기). */
export interface AnalyzeContentInput extends BaseConfig {
  subject: string;
  from: string;
  body: string;
  autoGenerated: boolean;
  includeCategory: boolean;
  includeSummary: boolean;
}

/** To/CC 에서 [나]의 위치. UNKNOWN = 받는 사람 정보 없음(블록 생략). */
export type RecipientRole = 'TO' | 'CC' | 'NONE' | 'UNKNOWN';

/**
 * ④ 개인 분석 입력. WP-149 는 [나] 주소·받는 사람 위치까지. WP-150 이 me(이름·직함·소속)·보낸 사람 관계·이전 메일·연결 이슈·첨부를
 * 덧붙인다 — 블록은 buildPersonalUserMessage 에 순서대로 추가한다.
 */
export interface AnalyzePersonalInput extends BaseConfig {
  subject: string;
  fromAddress: string;
  fromName: string;
  body: string;
  autoGenerated: boolean;
  me: { addresses: string[] };
  recipient: { myRole: RecipientRole; toCount: number; ccCount: number };
  includeNeedsReply: boolean;
  includePersonalSummary: boolean;
  includeCategory: boolean;
}

/** ③ user message — [제목]·[보낸 사람]·([자동 발송])·[본문]. */
export function buildContentUserMessage(input: AnalyzeContentInput): string {
  const lines = [`[제목] ${input.subject}`, `[보낸 사람] ${input.from}`];
  if (input.autoGenerated) lines.push('[자동 발송] 예');
  lines.push('[본문]', input.body);
  return lines.join('\n');
}

/** [받는 사람] 줄 — 위치를 모르면 null(블록 생략). */
function recipientLine(r: AnalyzePersonalInput['recipient']): string | null {
  const counts = `To ${r.toCount}명 · CC ${r.ccCount}명`;
  switch (r.myRole) {
    case 'TO':
      return `[받는 사람] 나는 To · ${counts}`;
    case 'CC':
      return `[받는 사람] 나는 CC · ${counts}`;
    case 'NONE':
      return `[받는 사람] 나는 To·CC 에 없음 · ${counts}`;
    default:
      return null;
  }
}

/** ④ user message — [나]·[보낸 사람]·[받는 사람]·[제목]·([자동 발송])·[본문]. 비어 있는 블록은 뺀다. */
export function buildPersonalUserMessage(input: AnalyzePersonalInput): string {
  const lines: string[] = [];
  if (input.me.addresses.length > 0) lines.push(`[나] 주소: ${input.me.addresses.join(', ')}`);
  const sender = input.fromName ? `${input.fromName} <${input.fromAddress}>` : input.fromAddress;
  lines.push(`[보낸 사람] ${sender}`);
  const recipient = recipientLine(input.recipient);
  if (recipient) lines.push(recipient);
  lines.push(`[제목] ${input.subject}`);
  if (input.autoGenerated) lines.push('[자동 발송] 예');
  lines.push('[본문]', input.body);
  return lines.join('\n');
}

// ③ 원본 분석: {category?, summary?}
export async function runMailAnalyzeContent(
  input: AnalyzeContentInput,
  deps: RunAgentDeps,
): Promise<{ category: string | null; summary: string | null }> {
  const flags = { includeCategory: input.includeCategory, includeSummary: input.includeSummary };
  const text = await runText(buildContentAnalysisPrompt(flags), buildContentUserMessage(input), input, deps, 'mail-analyze-content');
  return parseContentAnalysisJson(text, flags);
}

// ④ 개인 분석: {needsReply?, personalSummary?, personalSummaryValid, category?}
export async function runMailAnalyzePersonal(
  input: AnalyzePersonalInput,
  deps: RunAgentDeps,
): Promise<{ needsReply: boolean | null; personalSummary: string | null; personalSummaryValid: boolean; category: string | null }> {
  const flags = {
    includeNeedsReply: input.includeNeedsReply,
    includePersonalSummary: input.includePersonalSummary,
    includeCategory: input.includeCategory,
  };
  const text = await runText(buildPersonalAnalysisPrompt(flags), buildPersonalUserMessage(input), input, deps, 'mail-analyze-personal');
  return parsePersonalAnalysisJson(text, flags);
}
