package com.workplace.mail.util;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/** WP-149 ② 헤더 판정 — 대량·자동 발송 헤더 목록이 스펙과 일치하는지 고정한다. */
class AutoGeneratedHeadersTest {

  /** 헤더 맵(이름 대소문자 무시) → 조회 함수. */
  private static boolean detect(Map<String, String> headers) {
    Map<String, List<String>> lower = new HashMap<>();
    headers.forEach((k, v) -> lower.put(k.toLowerCase(Locale.ROOT), List.of(v)));
    return AutoGeneratedHeaders.detect(
        name -> lower.getOrDefault(name.toLowerCase(Locale.ROOT), List.of()));
  }

  @Test
  void noHeaders_isHuman() {
    assertThat(detect(Map.of())).isFalse();
  }

  @Test
  void listUnsubscribe_isAuto() {
    assertThat(detect(Map.of("List-Unsubscribe", "<mailto:u@example.com>"))).isTrue();
  }

  @Test
  void listId_isAuto() {
    assertThat(detect(Map.of("list-id", "<news.example.com>"))).isTrue();
  }

  @Test
  void xAutoResponseSuppress_isAuto() {
    assertThat(detect(Map.of("X-Auto-Response-Suppress", "All"))).isTrue();
  }

  @ParameterizedTest
  @ValueSource(strings = {"bulk", "list", "junk", " Bulk "})
  void bulkPrecedence_isAuto(String value) {
    assertThat(detect(Map.of("Precedence", value))).isTrue();
  }

  @Test
  void otherPrecedence_isHuman() {
    assertThat(detect(Map.of("Precedence", "first-class"))).isFalse();
  }

  @ParameterizedTest
  @ValueSource(strings = {"auto-replied", "auto-generated", "auto-notified; owner-email=a@b"})
  void autoSubmittedNotNo_isAuto(String value) {
    assertThat(detect(Map.of("Auto-Submitted", value))).isTrue();
  }

  @ParameterizedTest
  @ValueSource(strings = {"no", "NO", "no; comment"})
  void autoSubmittedNo_isHuman(String value) {
    assertThat(detect(Map.of("Auto-Submitted", value))).isFalse();
  }

  @Test
  void blankValues_areIgnored() {
    assertThat(detect(Map.of("List-Unsubscribe", "  ", "Auto-Submitted", " "))).isFalse();
  }
}
