package com.workplace.mail.util;

import static org.assertj.core.api.Assertions.assertThat;

import com.workplace.mail.util.NeedsReplyRules.Input;
import com.workplace.mail.util.NeedsReplyRules.RecipientRole;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/** WP-149 ⑤ 최종 판정 규칙 — 규칙별 경계와 고정 목록. */
class NeedsReplyRulesTest {

  private static final Set<String> ME = Set.of("gd@acme.com", "gd@gmail.com");

  /** 기본: 사람이 나에게 To 로 보낸 업무 메일. */
  private static Input input(String from, String to, String cc, boolean auto, String category) {
    return Input.of(from, ME, to, cc, auto, category);
  }

  private static Input human() {
    return input("minsu@acme.com", "gd@acme.com", null, false, "업무");
  }

  @Test
  void rawNull_staysNull() {
    assertThat(NeedsReplyRules.finalValue(null, human())).isNull();
  }

  @Test
  void rawFalse_staysFalse() {
    assertThat(NeedsReplyRules.finalValue(false, human())).isFalse();
  }

  @Test
  void rawTrue_humanToMe_isTrue() {
    assertThat(NeedsReplyRules.finalValue(true, human())).isTrue();
  }

  @Test
  void senderIsMe_caseInsensitive_isFalse() {
    assertThat(
            NeedsReplyRules.finalValue(
                true, input("GD@Gmail.com", "gd@acme.com", null, false, "업무")))
        .isFalse();
  }

  @ParameterizedTest
  @ValueSource(
      strings = {
        "noreply@x.com",
        "no-reply@x.com",
        "donotreply@x.com",
        "do-not-reply@x.com",
        "mailer-daemon@x.com",
        "postmaster@x.com",
        "bounce@x.com",
        "bounces@x.com",
        "NoReply@X.com",
        "bounces+123@x.com"
      })
  void autoLocalPart_isFalse(String from) {
    assertThat(NeedsReplyRules.finalValue(true, input(from, "gd@acme.com", null, false, "업무")))
        .isFalse();
  }

  @ParameterizedTest
  @ValueSource(strings = {"info@x.com", "replies@x.com", "noreply-team@x.com"})
  void otherLocalPart_isKept(String from) {
    assertThat(NeedsReplyRules.finalValue(true, input(from, "gd@acme.com", null, false, "업무")))
        .isTrue();
  }

  @Test
  void autoLocalParts_listIsFixed() {
    assertThat(NeedsReplyRules.AUTO_LOCAL_PARTS)
        .containsExactlyInAnyOrder(
            "noreply",
            "no-reply",
            "donotreply",
            "do-not-reply",
            "mailer-daemon",
            "postmaster",
            "bounce",
            "bounces");
  }

  @Test
  void autoGenerated_isFalse() {
    assertThat(
            NeedsReplyRules.finalValue(
                true, input("minsu@acme.com", "gd@acme.com", null, true, "업무")))
        .isFalse();
  }

  @Test
  void notInToOrCc_isFalse() {
    assertThat(
            NeedsReplyRules.finalValue(
                true, input("minsu@acme.com", "team@acme.com", "boss@acme.com", false, "업무")))
        .isFalse();
  }

  @Test
  void ccOnly_isLeftToLlm() {
    assertThat(
            NeedsReplyRules.finalValue(
                true,
                input("minsu@acme.com", "team@acme.com", "\"홍길동\" <GD@acme.com>", false, "업무")))
        .isTrue();
  }

  @Test
  void notAddressed_skippedWhenRecipientsUnknown() {
    assertThat(NeedsReplyRules.finalValue(true, input("minsu@acme.com", null, "  ", false, "업무")))
        .isTrue();
  }

  @Test
  void notAddressed_skippedWhenNoOwnAddress() {
    Input in = Input.of("minsu@acme.com", Set.of(), "team@acme.com", null, false, "업무");
    assertThat(NeedsReplyRules.finalValue(true, in)).isTrue();
  }

  @Test
  void myAddresses_normalizedInsideInput() {
    // 호출부가 대소문자 섞인 주소·null 을 넘겨도 규칙이 같은 결과를 내야 한다
    Input mixed = Input.of("GD@Acme.com", Set.of("Gd@ACME.com"), "x@acme.com", null, false, "업무");
    assertThat(NeedsReplyRules.finalValue(true, mixed)).isFalse();
    Input nullMine = Input.of("minsu@acme.com", null, "team@acme.com", null, false, "업무");
    assertThat(NeedsReplyRules.finalValue(true, nullMine)).isTrue();
  }

  @ParameterizedTest
  @ValueSource(strings = {"알림", "프로모션", "뉴스레터"})
  void nonReplyCategory_isFalse(String category) {
    assertThat(
            NeedsReplyRules.finalValue(
                true, input("minsu@acme.com", "gd@acme.com", null, false, category)))
        .isFalse();
  }

  @Test
  void missingCategory_conditionSkipped() {
    assertThat(
            NeedsReplyRules.finalValue(
                true, input("minsu@acme.com", "gd@acme.com", null, false, null)))
        .isTrue();
  }

  @Test
  void blockedByRules_excludesCategory() {
    assertThat(
            NeedsReplyRules.blockedByRules(
                input("minsu@acme.com", "gd@acme.com", null, false, "알림")))
        .isFalse();
    assertThat(NeedsReplyRules.blockedByCategory("알림")).isTrue();
  }

  @Test
  void recipientRole() {
    assertThat(NeedsReplyRules.recipientRole(human())).isEqualTo(RecipientRole.TO);
    assertThat(
            NeedsReplyRules.recipientRole(input("a@b.com", "x@y.com", "gd@gmail.com", false, null)))
        .isEqualTo(RecipientRole.CC);
    assertThat(NeedsReplyRules.recipientRole(input("a@b.com", "x@y.com", null, false, null)))
        .isEqualTo(RecipientRole.NONE);
    assertThat(NeedsReplyRules.recipientRole(input("a@b.com", null, null, false, null)))
        .isEqualTo(RecipientRole.UNKNOWN);
  }
}
