// 7d·WP-149: 메일 AI 라우트 테스트 — analyze-content/analyze-personal/reply-draft/draft-coaching/issue-draft 400/200/502 검증.
import { describe, it, expect, vi, beforeEach } from 'vitest';
import express from 'express';
import request from 'supertest';

vi.mock('../agent/run-mail-ai.js', () => ({
  runMailReplyDraft: vi.fn(),
  runMailDraftCoaching: vi.fn(),
  runMailIssueDraft: vi.fn(),
  runMailAnalyzeContent: vi.fn(),
  runMailAnalyzePersonal: vi.fn(),
}));

import { createMailRouter } from './mail.js';
import {
  runMailAnalyzeContent,
  runMailAnalyzePersonal,
  runMailReplyDraft,
  runMailDraftCoaching,
} from '../agent/run-mail-ai.js';

function app() {
  const a = express();
  a.use(express.json());
  a.use(createMailRouter({ client: {} as never }));
  return a;
}

beforeEach(() => vi.clearAllMocks());

describe('제거된 엔드포인트', () => {
  it.each(['/mail/classify', '/mail/summarize'])('%s 는 404', async (path) => {
    const res = await request(app()).post(path).send({});
    expect(res.status).toBe(404);
  });
});

describe('POST /mail/reply-draft', () => {
  const valid = {
    thread: [{ from: 'a@b', date: '2024-01-01', body: 'hello' }],
    replyingAs: 'me@example.com',
    assistantAgentId: 7,
    model: 'm',
    maxTurns: 1,
    timeoutMs: 60000,
  };
  it('정상 200 + 결과', async () => {
    vi.mocked(runMailReplyDraft).mockResolvedValue({ draftBody: '답장 초안' });
    const res = await request(app()).post('/mail/reply-draft').send(valid);
    expect(res.status).toBe(200);
    expect(res.body).toEqual({ draftBody: '답장 초안' });
  });
  it('스키마 위반 400', async () => {
    const res = await request(app()).post('/mail/reply-draft').send({ replyingAs: 'me@example.com' });
    expect(res.status).toBe(400);
  });
  it('러너 실패 502', async () => {
    vi.mocked(runMailReplyDraft).mockRejectedValue(new Error('boom'));
    const res = await request(app()).post('/mail/reply-draft').send(valid);
    expect(res.status).toBe(502);
  });
});

describe('POST /mail/draft-coaching', () => {
  const valid = {
    draftBody: '빨리 보내',
    thread: [],
    replyingAs: 'me@example.com',
    assistantAgentId: 7,
    model: 'm',
    maxTurns: 1,
    timeoutMs: 60000,
  };
  it('정상 200 + 결과', async () => {
    vi.mocked(runMailDraftCoaching).mockResolvedValue({
      notes: [{ dimension: 'TONE', message: '명령조' }],
      improvedBodyHtml: '<p>개선</p>',
    });
    const res = await request(app()).post('/mail/draft-coaching').send(valid);
    expect(res.status).toBe(200);
    expect(res.body).toEqual({ notes: [{ dimension: 'TONE', message: '명령조' }], improvedBodyHtml: '<p>개선</p>' });
  });
  it('스키마 위반 400', async () => {
    const res = await request(app()).post('/mail/draft-coaching').send({ draftBody: 'x' });
    expect(res.status).toBe(400);
  });
  it('러너 실패 502', async () => {
    vi.mocked(runMailDraftCoaching).mockRejectedValue(new Error('boom'));
    const res = await request(app()).post('/mail/draft-coaching').send(valid);
    expect(res.status).toBe(502);
  });
});

describe('POST /mail/analyze-content', () => {
  const valid = {
    subject: 's', from: 'a@b', body: 'x', autoGenerated: false, includeCategory: true, includeSummary: false,
    assistantAgentId: 7, model: 'm', maxTurns: 1, timeoutMs: 60000,
  };
  it('정상 200 + 결과', async () => {
    vi.mocked(runMailAnalyzeContent).mockResolvedValue({ category: '업무', summary: null });
    const res = await request(app()).post('/mail/analyze-content').send(valid);
    expect(res.status).toBe(200);
    expect(res.body).toEqual({ category: '업무', summary: null });
  });
  it('필드 누락 400', async () => {
    const res = await request(app()).post('/mail/analyze-content').send({ subject: 's' });
    expect(res.status).toBe(400);
  });
  it('받을 항목이 하나도 없으면 400', async () => {
    const res = await request(app()).post('/mail/analyze-content').send({ ...valid, includeCategory: false, includeSummary: false });
    expect(res.status).toBe(400);
  });
  it('러너 실패 502', async () => {
    vi.mocked(runMailAnalyzeContent).mockRejectedValue(new Error('boom'));
    const res = await request(app()).post('/mail/analyze-content').send(valid);
    expect(res.status).toBe(502);
  });
});

describe('POST /mail/analyze-personal', () => {
  const valid = {
    subject: 's', fromAddress: 'a@b.com', fromName: '', body: 'x', autoGenerated: false,
    me: { addresses: ['me@x.com'] }, recipient: { myRole: 'TO', toCount: 1, ccCount: 0 },
    includeNeedsReply: true, includePersonalSummary: false, includeCategory: false,
    assistantAgentId: 7, model: 'm', maxTurns: 1, timeoutMs: 60000,
  };
  it('정상 200 + 결과', async () => {
    vi.mocked(runMailAnalyzePersonal).mockResolvedValue({ needsReply: true, personalSummary: null, personalSummaryValid: false, category: null });
    const res = await request(app()).post('/mail/analyze-personal').send(valid);
    expect(res.status).toBe(200);
    expect(res.body.needsReply).toBe(true);
  });
  it('모르는 키는 무시하고 200', async () => {
    vi.mocked(runMailAnalyzePersonal).mockResolvedValue({ needsReply: false, personalSummary: null, personalSummaryValid: false, category: null });
    const res = await request(app()).post('/mail/analyze-personal').send({ ...valid, futureField: 1 });
    expect(res.status).toBe(200);
  });
  it('WP-150 보강 블록을 받아 러너에 넘긴다', async () => {
    vi.mocked(runMailAnalyzePersonal).mockResolvedValue({ needsReply: true, personalSummary: null, personalSummaryValid: false, category: null });
    const res = await request(app())
      .post('/mail/analyze-personal')
      .send({
        ...valid,
        me: { addresses: ['me@x.com'], name: '홍길동', otherNames: [], title: '팀장', groups: ['개발팀'] },
        sender: { relation: 'MEMBER', name: '김민수', title: null, organization: null, sameGroups: ['개발팀'], favorite: true },
        thread: [{ fromMe: true, from: 'me@x.com', date: '2026-09-30T00:00Z', body: '이전' }],
        linkedIssue: { key: 'WP-1', title: 't', status: 'TODO' },
        attachments: ['a.pdf'],
      });
    expect(res.status).toBe(200);
    const input = vi.mocked(runMailAnalyzePersonal).mock.calls[0][0];
    expect(input.me.name).toBe('홍길동');
    expect(input.sender?.relation).toBe('MEMBER');
    expect(input.thread).toHaveLength(1);
    expect(input.linkedIssue?.key).toBe('WP-1');
    expect(input.attachments).toEqual(['a.pdf']);
  });
  it('보강 블록이 null 이어도 200(api 가 조회 실패 블록을 비워 보냄)', async () => {
    vi.mocked(runMailAnalyzePersonal).mockResolvedValue({ needsReply: false, personalSummary: null, personalSummaryValid: false, category: null });
    const res = await request(app())
      .post('/mail/analyze-personal')
      .send({
        ...valid,
        me: { addresses: ['me@x.com'], name: null, otherNames: null, title: null, groups: null },
        sender: null,
        thread: null,
        linkedIssue: null,
        attachments: null,
      });
    expect(res.status).toBe(200);
  });
  it('이전 메일 6건·첨부 21개는 버리지 않고 5건·20개로 자른다', async () => {
    vi.mocked(runMailAnalyzePersonal).mockResolvedValue({ needsReply: false, personalSummary: null, personalSummaryValid: false, category: null });
    const thread = Array.from({ length: 6 }, (_, i) => ({ fromMe: false, from: 'a', date: 'd', body: `b${i}` }));
    const attachments = Array.from({ length: 21 }, (_, i) => `f${i}.pdf`);
    const res = await request(app()).post('/mail/analyze-personal').send({ ...valid, thread, attachments });
    expect(res.status).toBe(200);
    const input = vi.mocked(runMailAnalyzePersonal).mock.calls[0][0];
    expect(input.thread).toHaveLength(5);
    expect(input.thread?.[4].body).toBe('b4');
    expect(input.attachments).toHaveLength(20);
  });
  it('형식이 틀린 보강 블록은 그 블록만 버리고 200', async () => {
    vi.mocked(runMailAnalyzePersonal).mockResolvedValue({ needsReply: false, personalSummary: null, personalSummaryValid: false, category: null });
    const res = await request(app())
      .post('/mail/analyze-personal')
      .send({ ...valid, sender: { relation: 'BOSS' }, thread: [{ from: 'x' }], attachments: ['a.pdf'] });
    expect(res.status).toBe(200);
    const input = vi.mocked(runMailAnalyzePersonal).mock.calls[0][0];
    expect(input.sender).toBeUndefined();
    expect(input.thread).toBeUndefined();
    expect(input.attachments).toEqual(['a.pdf']);
  });
  it('myRole 이 정의 밖이면 400', async () => {
    const res = await request(app()).post('/mail/analyze-personal').send({ ...valid, recipient: { myRole: 'BCC', toCount: 0, ccCount: 0 } });
    expect(res.status).toBe(400);
  });
  it('받을 항목이 하나도 없으면 400', async () => {
    const res = await request(app())
      .post('/mail/analyze-personal')
      .send({ ...valid, includeNeedsReply: false, includePersonalSummary: false, includeCategory: false });
    expect(res.status).toBe(400);
  });
  it('러너 실패 502', async () => {
    vi.mocked(runMailAnalyzePersonal).mockRejectedValue(new Error('boom'));
    const res = await request(app()).post('/mail/analyze-personal').send(valid);
    expect(res.status).toBe(502);
  });
});
