// 7d: 메일 AI 라우트 — workplace-api 가 동기 호출. 도구 없이 텍스트 in/out.
// assistant 설정(assistantAgentId/model/maxTurns/timeoutMs)은 본문으로 온다. 미설정 503 분기는 api 소유.
import { Router, type Request, type Response } from 'express';
import { z } from 'zod';

import { type RunAgentDeps } from '../agent/run-agent.js';
import {
  runMailAnalyzeContent,
  runMailAnalyzePersonal,
  runMailDraftCoaching,
  runMailIssueDraft,
  runMailReplyDraft,
} from '../agent/run-mail-ai.js';

// 공통 assistant 설정 필드 — 모든 엔드포인트에서 공유.
const baseConfig = {
  assistantAgentId: z.number().int().positive(),
  model: z.string().min(1),
  maxTurns: z.number().int().positive(),
  timeoutMs: z.number().int().positive(),
};

export const replyDraftSchema = z.object({
  thread: z.array(z.object({ from: z.string(), date: z.string(), body: z.string() })),
  replyingAs: z.string(),
  ...baseConfig,
});
export const coachDraftSchema = z.object({
  draftBody: z.string(),
  thread: z.array(z.object({ from: z.string(), date: z.string(), body: z.string() })),
  replyingAs: z.string(),
  ...baseConfig,
});
export const issueDraftSchema = z.object({
  subject: z.string(),
  body: z.string(),
  candidateProjects: z.array(z.object({ key: z.string(), name: z.string() })),
  ...baseConfig,
});

// WP-149 받을 항목이 하나도 없으면 호출 자체가 무의미 — 400.
const atLeastOne = (keys: string[]) => (v: Record<string, unknown>) => keys.some((k) => v[k] === true);

// WP-149 ③ 원본 분석. 모르는 키는 zod 가 버린다.
export const analyzeContentSchema = z
  .object({
    subject: z.string(),
    from: z.string(),
    body: z.string(),
    autoGenerated: z.boolean(),
    includeCategory: z.boolean(),
    includeSummary: z.boolean(),
    ...baseConfig,
  })
  .refine(atLeastOne(['includeCategory', 'includeSummary']), { message: '받을 항목(include*)이 하나 이상 필요합니다' });

// WP-150 ④ 보강 블록 — 모두 선택(nullish). 구버전 api 는 보내지 않고, 조회에 실패한 블록은 null 로 온다.
// 형식이 틀린 블록은 .catch 로 그 블록만 버린다 — 블록 하나 때문에 400 이 나면 api 가 시도를 기록하지 못해 매 백필마다 재시도한다.
const optionalText = z.string().nullish().catch(undefined);
const optionalTexts = z.array(z.string()).nullish().catch(undefined);

const meSchema = z.object({
  addresses: z.array(z.string()),
  name: optionalText,
  otherNames: optionalTexts,
  title: optionalText,
  groups: optionalTexts,
});

const senderSchema = z.object({
  relation: z.enum(['SELF', 'MEMBER', 'CONTACT', 'UNKNOWN']),
  name: optionalText,
  title: optionalText,
  organization: optionalText,
  sameGroups: optionalTexts,
  favorite: z.boolean().nullish().catch(undefined),
});

const priorMailSchema = z.object({ fromMe: z.boolean(), from: z.string(), date: z.string(), body: z.string() });

const linkedIssueSchema = z.object({ key: z.string(), title: z.string(), status: z.string() });

// WP-149 ④ 개인 분석 + WP-150 보강 블록. 모르는 키는 zod 가 버린다.
export const analyzePersonalSchema = z
  .object({
    subject: z.string(),
    fromAddress: z.string(),
    fromName: z.string(),
    body: z.string(),
    autoGenerated: z.boolean(),
    me: meSchema,
    recipient: z.object({
      myRole: z.enum(['TO', 'CC', 'NONE', 'UNKNOWN']),
      toCount: z.number().int().nonnegative(),
      ccCount: z.number().int().nonnegative(),
    }),
    sender: senderSchema.nullish().catch(undefined),
    thread: z.array(priorMailSchema).max(5).nullish().catch(undefined),
    linkedIssue: linkedIssueSchema.nullish().catch(undefined),
    attachments: z.array(z.string()).max(20).nullish().catch(undefined),
    includeNeedsReply: z.boolean(),
    includePersonalSummary: z.boolean(),
    includeCategory: z.boolean(),
    ...baseConfig,
  })
  .refine(atLeastOne(['includeNeedsReply', 'includePersonalSummary', 'includeCategory']), {
    message: '받을 항목(include*)이 하나 이상 필요합니다',
  });

// 공통 핸들러 팩토리 — zod 검증 → 러너 호출 → 400/200/502 응답. drive 등 타 라우터에서도 재사용.
export function handler<T>(
  schema: z.ZodType<T>,
  run: (input: T, deps: RunAgentDeps) => Promise<unknown>,
  deps: RunAgentDeps,
  tag: string,
) {
  return async (req: Request, res: Response): Promise<void> => {
    const parsed = schema.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({ error: 'invalid_payload', issues: parsed.error.issues });
      return;
    }
    try {
      res.status(200).json(await run(parsed.data, deps));
    } catch (e) {
      console.error(`[${tag}] 실패:`, e instanceof Error ? e.message : String(e));
      res.status(502).json({ error: `${tag}_failed` });
    }
  };
}

export function createMailRouter(deps: RunAgentDeps): Router {
  const router = Router();

  // WP-149 ③ 원본 분석: {category, summary} — 원본별 1회(공통 비서).
  router.post('/mail/analyze-content', handler(analyzeContentSchema, runMailAnalyzeContent, deps, 'mail-analyze-content'));
  // WP-149 ④ 개인 분석: {needsReply, personalSummary, personalSummaryValid, category} — 사본별 1회(개인→공통 비서).
  router.post('/mail/analyze-personal', handler(analyzePersonalSchema, runMailAnalyzePersonal, deps, 'mail-analyze-personal'));

  // 답장 초안 생성: draft 텍스트 반환.
  router.post('/mail/reply-draft', handler(replyDraftSchema, runMailReplyDraft, deps, 'mail-reply-draft'));
  // 초안 코칭: notes + improvedBodyHtml 반환.
  router.post('/mail/draft-coaching', handler(coachDraftSchema, runMailDraftCoaching, deps, 'mail-draft-coaching'));
  // #520 메일→이슈 초안: title/body/priority/projectKey 반환.
  router.post('/mail/issue-draft', handler(issueDraftSchema, runMailIssueDraft, deps, 'mail-issue-draft'));

  return router;
}
