spring:
  application:
    name: workplace-api
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  jooq:
    sql-dialect: postgres

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
